//! MIR to textual LLVM IR.
//!
//! Every MIR local gets a stack slot; LLVM's optimizer promotes them to
//! registers. Runtime checks (integer overflow, division by zero, shift
//! counts, conversion ranges) branch to MIR cleanup with the source location.
//! Features the backend cannot compile yet are reported as diagnostics instead
//! of being miscompiled.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write;

use crate::ast::{BinaryOp, UnaryOp};
use crate::diagnostic::{Diagnostic, Severity};
use crate::hir::{self, Const};
use crate::mir::{self, Callee, Local, Operand, Place, Rvalue, Terminator};
use crate::source::{SourceFile, Span};
use crate::types::{IntType, TypeId, TypeKind};

pub fn emit(
    package: &hir::Package,
    program: &mir::Program,
    file: &SourceFile,
) -> Result<String, Vec<Diagnostic>> {
    let mut module = Module {
        package,
        file,
        strings: HashMap::new(),
        intrinsics: BTreeSet::new(),
        globals: String::new(),
        diagnostics: Vec::new(),
    };
    let mut functions = String::new();
    for body in &program.bodies {
        functions.push_str(&module.function(body));
    }
    if !module.diagnostics.is_empty() {
        return Err(module.diagnostics);
    }
    let mut out = String::from("; Generated by the Zore bootstrap compiler.\n\n");
    for strukt in &package.structs {
        let fields: Vec<String> = strukt.fields.iter().map(|f| module.ty(f.ty)).collect();
        writeln!(
            out,
            "%\"{}.{}\" = type {{ {} }}",
            package.name,
            strukt.name,
            fields.join(", ")
        )
        .unwrap();
        let flag_fields: Vec<String> = strukt.fields.iter().map(|f| module.flag_ty(f.ty)).collect();
        let fields = std::iter::once("i1".to_string())
            .chain(flag_fields)
            .collect::<Vec<_>>();
        writeln!(
            out,
            "%\"{}.DropFlags.{}\" = type {{ {} }}",
            package.name,
            strukt.name,
            fields.join(", ")
        )
        .unwrap();
    }
    out.push('\n');
    out.push_str(&module.globals);
    out.push_str(RUNTIME_DECLARATIONS);
    for intrinsic in &module.intrinsics {
        out.push_str(intrinsic);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&functions);
    if let Some(entry) = program.entry {
        let name = &package.function(entry).name;
        writeln!(
            out,
            "define void @zore_entry() {{\nentry:\n  call void @\"{}.{name}\"()\n  ret void\n}}",
            package.name
        )
        .unwrap();
    }
    Ok(out)
}

const RUNTIME_DECLARATIONS: &str = "\
declare void @zore_println_str(ptr, i64)
declare void @zore_println_i64(i64)
declare void @zore_println_u64(i64)
declare void @zore_println_bool(i1 zeroext)
declare void @zore_println_rune(i32)
declare i32 @zore_string_compare(ptr, i64, ptr, i64)
declare void @zore_raise_panic(ptr, i64)
declare zeroext i1 @zore_panic_pending()
declare void @zore_enter_drop()
declare void @zore_leave_drop()
declare void @zore_abort() noreturn
declare double @llvm.trunc.f64(double)
declare double @llvm.fabs.f64(double)
";

struct Module<'a> {
    package: &'a hir::Package,
    file: &'a SourceFile,
    strings: HashMap<Vec<u8>, String>,
    intrinsics: BTreeSet<String>,
    globals: String,
    diagnostics: Vec<Diagnostic>,
}

impl Module<'_> {
    fn flag_ty(&self, ty: TypeId) -> String {
        match self.package.types.kind(ty) {
            TypeKind::Struct(id) => {
                format!("%\"{}.DropFlags.{}\"", self.package.name, self.package.strukt(id).name)
            }
            _ => "i1".into(),
        }
    }

    fn ty(&self, ty: TypeId) -> String {
        match self.package.types.kind(ty) {
            TypeKind::Bool => "i1".into(),
            TypeKind::Int(int) => format!("i{}", int.bits),
            TypeKind::Float(float) if float.bits == 32 => "float".into(),
            TypeKind::Float(_) => "double".into(),
            TypeKind::Rune => "i32".into(),
            TypeKind::String => "{ ptr, i64 }".into(),
            TypeKind::Struct(id) => {
                format!(
                    "%\"{}.{}\"",
                    self.package.name,
                    self.package.strukt(id).name
                )
            }
        }
    }

    fn results_ty(&self, results: &[TypeId]) -> String {
        match results {
            [] => "void".into(),
            [one] => self.ty(*one),
            many => {
                let fields: Vec<String> = many.iter().map(|&t| self.ty(t)).collect();
                format!("{{ {} }}", fields.join(", "))
            }
        }
    }

    fn string_global(&mut self, bytes: &[u8]) -> String {
        if let Some(name) = self.strings.get(bytes) {
            return name.clone();
        }
        let name = format!("@str.{}", self.strings.len());
        let mut escaped = String::new();
        for &b in bytes {
            if b.is_ascii_graphic() && b != b'"' && b != b'\\' || b == b' ' {
                escaped.push(b as char);
            } else {
                write!(escaped, "\\{b:02X}").unwrap();
            }
        }
        writeln!(
            self.globals,
            "{name} = private unnamed_addr constant [{} x i8] c\"{escaped}\"",
            bytes.len()
        )
        .unwrap();
        self.strings.insert(bytes.to_vec(), name.clone());
        name
    }

    fn location(&self, span: Span) -> String {
        let at = self.file.location(span.start()).expect("span in file");
        format!("{}:{}:{}", self.file.path().display(), at.line, at.column)
    }

    fn overflow_intrinsic(&mut self, op: &str, ty: &str) -> String {
        let name = format!("@llvm.{op}.with.overflow.{ty}");
        self.intrinsics
            .insert(format!("declare {{ {ty}, i1 }} {name}({ty}, {ty})"));
        name
    }

    fn unsupported(&mut self, what: &str, span: Span, note: &str) {
        self.diagnostics.push(
            Diagnostic::new(
                Severity::Error,
                format!("{what} not supported by the native backend yet"),
                span,
            )
            .note(note.to_owned()),
        );
    }

    fn function(&mut self, body: &mir::Body) -> String {
        let mut f = FunctionBuilder {
            module: self,
            body,
            out: String::new(),
            next: 0,
            active_unwind: None,
            emitting_unwind: false,
        };
        f.emit();
        f.out
    }
}

struct FunctionBuilder<'m, 'a> {
    module: &'m mut Module<'a>,
    body: &'m mir::Body,
    out: String,
    next: u32,
    active_unwind: Option<mir::BlockId>,
    emitting_unwind: bool,
}

impl FunctionBuilder<'_, '_> {
    fn fresh(&mut self) -> String {
        self.next += 1;
        format!("%t{}", self.next)
    }

    fn label(&mut self) -> String {
        self.next += 1;
        format!("L{}", self.next)
    }

    fn line(&mut self, text: impl AsRef<str>) {
        self.out.push_str("  ");
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }

    fn ty(&self, ty: TypeId) -> String {
        self.module.ty(ty)
    }

    fn local_ty(&self, local: Local) -> TypeId {
        self.body.locals[local.0 as usize].ty
    }

    /// The LLVM type stored in a local's stack slot.
    fn slot_ty(&self, local: Local) -> String {
        if self.body.locals[local.0 as usize].by_reference {
            "ptr".into()
        } else {
            self.ty(self.local_ty(local))
        }
    }

    fn place_ty(&self, place: &Place) -> TypeId {
        let package = self.module.package;
        let mut ty = self.local_ty(place.local);
        for field in &place.fields {
            let id = package.types.struct_id(ty).expect("struct projection");
            ty = package.strukt(id).fields[field.0 as usize].ty;
        }
        ty
    }

    fn operand_ty(&self, operand: &Operand) -> TypeId {
        match operand {
            Operand::Copy(place) | Operand::Move(place) | Operand::Ref(place) => {
                self.place_ty(place)
            }
            Operand::Const(_, ty) => *ty,
        }
    }

    fn emit(&mut self) {
        let package = self.module.package;
        let function = package.function(self.body.function);
        let mut params = Vec::new();
        for &param in &self.body.params {
            params.push(format!("{} %p{}", self.slot_ty(param), param.0));
            if self.body.locals[param.0 as usize].by_reference
                && !package.is_copy(self.local_ty(param))
            {
                params.push(format!("ptr %pf{}", param.0));
            }
        }
        let header = format!(
            "define {} @\"{}.{}\"({}) {{\nentry:\n",
            self.module.results_ty(&function.results),
            package.name,
            self.body.name,
            params.join(", ")
        );
        self.out.push_str(&header);
        for index in 0..self.body.locals.len() {
            let ty = self.slot_ty(Local(index as u32));
            self.line(format!("%l{index} = alloca {ty}"));
            let local = Local(index as u32);
            if !package.is_copy(self.local_ty(local)) {
                let flags = if self.body.locals[index].by_reference {
                    "ptr".to_string()
                } else {
                    self.module.flag_ty(self.local_ty(local))
                };
                self.line(format!("%lf{index} = alloca {flags}"));
            }
        }
        for index in 0..self.body.locals.len() {
            let local = Local(index as u32);
            if !self.body.locals[index].by_reference && !package.is_copy(self.local_ty(local)) {
                self.set_flags(&Place::local(local), false);
            }
        }
        for &param in &self.body.params {
            let ty = self.slot_ty(param);
            self.line(format!("store {ty} %p{}, ptr %l{}", param.0, param.0));
            if !package.is_copy(self.local_ty(param)) {
                if self.body.locals[param.0 as usize].by_reference {
                    self.line(format!("store ptr %pf{}, ptr %lf{}", param.0, param.0));
                } else {
                    self.set_flags(&Place::local(param), true);
                }
            }
        }
        self.line("br label %bb0");
        for (index, block) in self.body.blocks.iter().enumerate() {
            self.emitting_unwind = self.body.unwind == Some(mir::BlockId(index as u32));
            self.out.push_str(&format!("bb{index}:\n"));
            for statement in &block.statements {
                self.statement(statement);
            }
            self.terminator(&block.terminator);
        }
        self.out.push_str("}\n\n");
    }

    fn address(&mut self, place: &Place) -> String {
        let mut base = format!("%l{}", place.local.0);
        if self.body.locals[place.local.0 as usize].by_reference {
            let referent = self.fresh();
            self.line(format!("{referent} = load ptr, ptr {base}"));
            base = referent;
        }
        if place.fields.is_empty() {
            return base;
        }
        let ty = self.ty(self.local_ty(place.local));
        let indices: String = place
            .fields
            .iter()
            .map(|f| format!(", i32 {}", f.0))
            .collect();
        let name = self.fresh();
        self.line(format!(
            "{name} = getelementptr inbounds {ty}, ptr {base}, i32 0{indices}"
        ));
        name
    }

    fn flag_address(&mut self, place: &Place) -> String {
        let mut current_ty = self.local_ty(place.local);
        let mut address = format!("%lf{}", place.local.0);
        if self.body.locals[place.local.0 as usize].by_reference {
            let loaded = self.fresh();
            self.line(format!("{loaded} = load ptr, ptr {address}"));
            address = loaded;
        }
        for field in &place.fields {
            let id = self.module.package.types.struct_id(current_ty).expect("struct flag projection");
            let projected = self.fresh();
            self.line(format!(
                "{projected} = getelementptr inbounds {}, ptr {address}, i32 0, i32 {}",
                self.module.flag_ty(current_ty),
                field.0 + 1
            ));
            address = projected;
            current_ty = self.module.package.strukt(id).fields[field.0 as usize].ty;
        }
        address
    }

    fn root_flag_address(&mut self, place: &Place) -> String {
        let address = self.flag_address(place);
        let ty = self.place_ty(place);
        if matches!(self.module.package.types.kind(ty), TypeKind::Struct(_)) {
            let root = self.fresh();
            self.line(format!(
                "{root} = getelementptr inbounds {}, ptr {address}, i32 0, i32 0",
                self.module.flag_ty(ty)
            ));
            root
        } else {
            address
        }
    }

    fn set_root_flag(&mut self, place: &Place, value: bool) {
        if self.module.package.is_copy(self.place_ty(place)) {
            return;
        }
        let address = self.root_flag_address(place);
        self.line(format!("store i1 {value}, ptr {address}"));
    }

    fn set_flags(&mut self, place: &Place, value: bool) {
        let ty = self.place_ty(place);
        if self.module.package.is_copy(ty) {
            return;
        }
        self.set_root_flag(place, value);
        if let TypeKind::Struct(id) = self.module.package.types.kind(ty) {
            let count = self.module.package.strukt(id).fields.len();
            for index in 0..count {
                let mut child = place.clone();
                child.fields.push(hir::FieldId(index as u32));
                self.set_flags(&child, value);
            }
        }
    }

    fn constant(&mut self, c: &Const) -> String {
        match c {
            Const::Bool(b) => b.to_string(),
            Const::Int(v) => v.to_string(),
            Const::Rune(r) => u32::from(*r).to_string(),
            Const::Float(x) => format!("0x{:016X}", x.to_bits()),
            Const::String(s) => {
                let global = self.module.string_global(s.as_bytes());
                format!("{{ ptr {global}, i64 {} }}", s.len())
            }
        }
    }

    fn value(&mut self, operand: &Operand) -> String {
        match operand {
            Operand::Const(c, _) => self.constant(c),
            Operand::Ref(_) => unreachable!("references are only call arguments"),
            Operand::Copy(place) | Operand::Move(place) => {
                let ty = self.ty(self.place_ty(place));
                let address = self.address(place);
                let name = self.fresh();
                self.line(format!("{name} = load {ty}, ptr {address}"));
                if matches!(operand, Operand::Move(_)) {
                    self.set_flags(place, false);
                }
                name
            }
        }
    }

    fn store(&mut self, place: &Place, value: &str) {
        let ty = self.ty(self.place_ty(place));
        let address = self.address(place);
        self.line(format!("store {ty} {value}, ptr {address}"));
        self.set_flags(place, true);
    }

    fn panic_if(&mut self, condition: &str, message: &str, span: Span) {
        let text = format!("{message} at {}", self.module.location(span));
        let global = self.module.string_global(text.as_bytes());
        let (fail, ok) = (self.label(), self.label());
        self.line(format!("br i1 {condition}, label %{fail}, label %{ok}"));
        self.out.push_str(&format!("{fail}:\n"));
        self.line(format!("call void @zore_raise_panic(ptr {global}, i64 {})", text.len()));
        let unwind = self.active_unwind.expect("checked operation has cleanup edge");
        self.line(format!("br label %bb{}", unwind.0));
        self.out.push_str(&format!("{ok}:\n"));
    }

    fn statement(&mut self, statement: &mir::Statement) {
        match statement {
            mir::Statement::Assign { place, rvalue, span } => {
                self.assign_rvalue(place, rvalue, *span);
            }
            mir::Statement::Drop { place, replacement } => {
                self.drop_place(place);
                if !self.emitting_unwind {
                    self.check_after_drop(*replacement && self.has_custom_ancestor(place));
                }
            }
            mir::Statement::EndScope(_) => unreachable!("drop insertion replaces scope markers"),
        }
    }

    fn assign_rvalue(&mut self, place: &Place, rvalue: &Rvalue, span: Span) {
        let result_ty = self.place_ty(place);
        let value = match rvalue {
            Rvalue::Use(operand) => self.value(operand),
            Rvalue::Binary(op, lhs, rhs) => self.binary(*op, lhs, rhs, span),
            Rvalue::Unary(op, operand) => self.unary(*op, operand, span),
            Rvalue::Convert(operand, to) => self.convert(operand, *to, span),
            Rvalue::Aggregate(_, operands) => {
                let ty = self.ty(result_ty);
                let mut current = "undef".to_string();
                for (index, operand) in operands.iter().enumerate() {
                    let field_ty = self.ty(self.operand_ty(operand));
                    let value = self.value(operand);
                    let name = self.fresh();
                    self.line(format!(
                        "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                    ));
                    current = name;
                }
                current
            }
        };
        self.store(place, &value);
    }

    fn drop_place(&mut self, place: &Place) {
        let ty = self.place_ty(place);
        if self.module.package.is_copy(ty) {
            return;
        }
        let flag = self.root_flag_address(place);
        let live = self.fresh();
        self.line(format!("{live} = load i1, ptr {flag}"));
        let (run, done) = (self.label(), self.label());
        self.line(format!("br i1 {live}, label %{run}, label %{done}"));
        self.out.push_str(&format!("{run}:\n"));
        self.line(format!("store i1 false, ptr {flag}"));
        if let TypeKind::Struct(id) = self.module.package.types.kind(ty) {
            let strukt = self.module.package.strukt(id);
            let drop = strukt.drop;
            let fields = strukt.fields.len();
            if let Some(drop) = drop {
                let name = self.module.package.function(drop).name.clone();
                let value_address = self.address(place);
                let flag_address = self.flag_address(place);
                self.line("call void @zore_enter_drop()");
                self.line(format!(
                    "call void @\"{}.{}\"(ptr {value_address}, ptr {flag_address})",
                    self.module.package.name,
                    name
                ));
                self.line("call void @zore_leave_drop()");
            }
            for index in (0..fields).rev() {
                let mut child = place.clone();
                child.fields.push(hir::FieldId(index as u32));
                self.drop_place(&child);
            }
        }
        self.line(format!("br label %{done}"));
        self.out.push_str(&format!("{done}:\n"));
    }

    fn has_custom_ancestor(&self, place: &Place) -> bool {
        let mut ty = self.local_ty(place.local);
        for field in &place.fields {
            let id = self.module.package.types.struct_id(ty).expect("field projection");
            if self.module.package.strukt(id).drop.is_some() {
                return true;
            }
            ty = self.module.package.strukt(id).fields[field.0 as usize].ty;
        }
        false
    }

    fn check_after_drop(&mut self, abort_on_panic: bool) {
        let pending = self.fresh();
        self.line(format!("{pending} = call zeroext i1 @zore_panic_pending()"));
        let (failed, ok) = (self.label(), self.label());
        self.line(format!("br i1 {pending}, label %{failed}, label %{ok}"));
        self.out.push_str(&format!("{failed}:\n"));
        if abort_on_panic {
            self.line("call void @zore_abort()");
            self.line("unreachable");
        } else {
            let unwind = self.body.unwind.expect("drop cleanup block");
            self.line(format!("br label %bb{}", unwind.0));
        }
        self.out.push_str(&format!("{ok}:\n"));
    }

    fn string_parts(&mut self, value: &str) -> (String, String) {
        let (ptr, len) = (self.fresh(), self.fresh());
        self.line(format!("{ptr} = extractvalue {{ ptr, i64 }} {value}, 0"));
        self.line(format!("{len} = extractvalue {{ ptr, i64 }} {value}, 1"));
        (ptr, len)
    }

    fn binary(&mut self, op: BinaryOp, lhs: &Operand, rhs: &Operand, span: Span) -> String {
        let operand_ty = self.operand_ty(lhs);
        let kind = self.module.package.types.kind(operand_ty);
        if matches!(op, BinaryOp::Shl | BinaryOp::Shr) {
            let TypeKind::Int(int) = kind else {
                unreachable!("checked shift")
            };
            return self.shift(op, int, lhs, rhs, span);
        }
        let (a, b) = (self.value(lhs), self.value(rhs));
        let ty = self.ty(operand_ty);
        let name = self.fresh();
        match kind {
            TypeKind::Int(int) => self.int_binary(op, int, &ty, &a, &b, span),
            TypeKind::Float(_) => {
                let instruction = match op {
                    BinaryOp::Add => "fadd",
                    BinaryOp::Sub => "fsub",
                    BinaryOp::Mul => "fmul",
                    BinaryOp::Div => "fdiv",
                    BinaryOp::Eq => "fcmp oeq",
                    BinaryOp::NotEq => "fcmp une",
                    BinaryOp::Lt => "fcmp olt",
                    BinaryOp::LtEq => "fcmp ole",
                    BinaryOp::Gt => "fcmp ogt",
                    BinaryOp::GtEq => "fcmp oge",
                    _ => unreachable!("checked float operator"),
                };
                self.line(format!("{name} = {instruction} {ty} {a}, {b}"));
                name
            }
            TypeKind::Bool | TypeKind::Rune => {
                let predicate = compare_predicate(op, false);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
                name
            }
            TypeKind::String => {
                if op == BinaryOp::Add {
                    self.module.unsupported(
                        "runtime string concatenation is",
                        span,
                        "string buffer allocation is not designed yet (§41.5); constant concatenation works",
                    );
                    return "undef".into();
                }
                let (ap, al) = self.string_parts(&a);
                let (bp, bl) = self.string_parts(&b);
                let ordering = self.fresh();
                self.line(format!(
                    "{ordering} = call i32 @zore_string_compare(ptr {ap}, i64 {al}, ptr {bp}, i64 {bl})"
                ));
                let predicate = compare_predicate(op, true);
                self.line(format!("{name} = icmp {predicate} i32 {ordering}, 0"));
                name
            }
            TypeKind::Struct(_) => unreachable!("structs have no operators"),
        }
    }

    fn int_binary(
        &mut self,
        op: BinaryOp,
        int: IntType,
        ty: &str,
        a: &str,
        b: &str,
        span: Span,
    ) -> String {
        let sign = if int.signed { "s" } else { "u" };
        let name = self.fresh();
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                let base = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    _ => "mul",
                };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}{base}"), ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} {a}, {ty} {b})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.panic_if(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            BinaryOp::Div | BinaryOp::Rem => {
                let zero = self.fresh();
                self.line(format!("{zero} = icmp eq {ty} {b}, 0"));
                self.panic_if(&zero, "division by zero", span);
                if int.signed {
                    let (is_min, is_neg_one, both) = (self.fresh(), self.fresh(), self.fresh());
                    self.line(format!("{is_min} = icmp eq {ty} {a}, {}", int.min()));
                    self.line(format!("{is_neg_one} = icmp eq {ty} {b}, -1"));
                    self.line(format!("{both} = and i1 {is_min}, {is_neg_one}"));
                    self.panic_if(&both, "integer overflow", span);
                }
                let instruction = if op == BinaryOp::Div { "div" } else { "rem" };
                self.line(format!("{name} = {sign}{instruction} {ty} {a}, {b}"));
            }
            BinaryOp::BitAnd => self.line(format!("{name} = and {ty} {a}, {b}")),
            BinaryOp::BitOr => self.line(format!("{name} = or {ty} {a}, {b}")),
            BinaryOp::BitXor => self.line(format!("{name} = xor {ty} {a}, {b}")),
            _ => {
                let predicate = compare_predicate(op, int.signed);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
            }
        }
        name
    }

    fn shift(
        &mut self,
        op: BinaryOp,
        int: IntType,
        lhs: &Operand,
        rhs: &Operand,
        span: Span,
    ) -> String {
        let ty = format!("i{}", int.bits);
        let value = self.value(lhs);
        let count_ty = self.operand_ty(rhs);
        let count_int = self
            .module
            .package
            .types
            .int(count_ty)
            .expect("integer count");
        let cty = format!("i{}", count_int.bits);
        let count = self.value(rhs);
        // An unsigned comparison also rejects a negative signed count.
        let invalid = self.fresh();
        self.line(format!("{invalid} = icmp uge {cty} {count}, {}", int.bits));
        self.panic_if(&invalid, "shift count out of range", span);
        let count = match count_int.bits.cmp(&int.bits) {
            std::cmp::Ordering::Equal => count,
            std::cmp::Ordering::Greater => {
                let name = self.fresh();
                self.line(format!("{name} = trunc {cty} {count} to {ty}"));
                name
            }
            std::cmp::Ordering::Less => {
                let name = self.fresh();
                self.line(format!("{name} = zext {cty} {count} to {ty}"));
                name
            }
        };
        let instruction = match (op, int.signed) {
            (BinaryOp::Shl, _) => "shl",
            (_, true) => "ashr",
            (_, false) => "lshr",
        };
        let name = self.fresh();
        self.line(format!("{name} = {instruction} {ty} {value}, {count}"));
        name
    }

    fn unary(&mut self, op: UnaryOp, operand: &Operand, span: Span) -> String {
        let operand_ty = self.operand_ty(operand);
        let ty = self.ty(operand_ty);
        let value = self.value(operand);
        let name = self.fresh();
        match (op, self.module.package.types.kind(operand_ty)) {
            (UnaryOp::Plus, _) => return value,
            (UnaryOp::Not, _) => self.line(format!("{name} = xor i1 {value}, true")),
            (UnaryOp::Complement, _) => self.line(format!("{name} = xor {ty} {value}, -1")),
            (UnaryOp::Neg, TypeKind::Float(_)) => self.line(format!("{name} = fneg {ty} {value}")),
            (UnaryOp::Neg, TypeKind::Int(int)) => {
                let sign = if int.signed { "s" } else { "u" };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}sub"), &ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} 0, {ty} {value})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.panic_if(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            _ => unreachable!("checked unary operator"),
        }
        name
    }

    fn convert(&mut self, operand: &Operand, to: TypeId, span: Span) -> String {
        let from = self.operand_ty(operand);
        let value = self.value(operand);
        if from == to {
            return value;
        }
        let types = &self.module.package.types;
        let (from_kind, to_kind) = (types.kind(from), types.kind(to));
        let (fty, tty) = (self.ty(from), self.ty(to));
        let name = self.fresh();
        match (from_kind, to_kind) {
            (TypeKind::Int(src), TypeKind::Int(dst)) => {
                let wide = self.fresh();
                let extend = if src.signed { "sext" } else { "zext" };
                self.line(format!("{wide} = {extend} {fty} {value} to i128"));
                let (low, high, outside) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{low} = icmp slt i128 {wide}, {}", dst.min()));
                self.line(format!("{high} = icmp sgt i128 {wide}, {}", dst.max()));
                self.line(format!("{outside} = or i1 {low}, {high}"));
                self.panic_if(&outside, "integer conversion out of range", span);
                match src.bits.cmp(&dst.bits) {
                    std::cmp::Ordering::Equal => return value,
                    std::cmp::Ordering::Greater => {
                        self.line(format!("{name} = trunc {fty} {value} to {tty}"))
                    }
                    std::cmp::Ordering::Less => {
                        self.line(format!("{name} = {extend} {fty} {value} to {tty}"))
                    }
                }
            }
            (TypeKind::Int(src), TypeKind::Float(_)) => {
                let instruction = if src.signed { "sitofp" } else { "uitofp" };
                self.line(format!("{name} = {instruction} {fty} {value} to {tty}"));
            }
            (TypeKind::Float(src), TypeKind::Int(dst)) => {
                let wide = if src.bits == 32 {
                    let w = self.fresh();
                    self.line(format!("{w} = fpext float {value} to double"));
                    w
                } else {
                    value
                };
                let truncated = self.fresh();
                self.line(format!(
                    "{truncated} = call double @llvm.trunc.f64(double {wide})"
                ));
                let low = format!("0x{:016X}", (dst.min() as f64).to_bits());
                let limit = format!("0x{:016X}", ((dst.max() + 1) as f64).to_bits());
                let (at_least, below, inside, outside) =
                    (self.fresh(), self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{at_least} = fcmp oge double {truncated}, {low}"));
                self.line(format!("{below} = fcmp olt double {truncated}, {limit}"));
                self.line(format!("{inside} = and i1 {at_least}, {below}"));
                self.line(format!("{outside} = xor i1 {inside}, true"));
                self.panic_if(&outside, "float to integer conversion out of range", span);
                let instruction = if dst.signed { "fptosi" } else { "fptoui" };
                self.line(format!(
                    "{name} = {instruction} double {truncated} to {tty}"
                ));
            }
            (TypeKind::Float(src), TypeKind::Float(dst)) if src.bits < dst.bits => {
                self.line(format!("{name} = fpext {fty} {value} to {tty}"));
            }
            (TypeKind::Float(_), TypeKind::Float(_)) => {
                self.line(format!("{name} = fptrunc {fty} {value} to {tty}"));
                let (source, result) = (self.fresh(), self.fresh());
                self.line(format!(
                    "{source} = call double @llvm.fabs.f64(double {value})"
                ));
                let narrowed = self.fresh();
                self.line(format!("{narrowed} = fpext {tty} {name} to double"));
                self.line(format!(
                    "{result} = call double @llvm.fabs.f64(double {narrowed})"
                ));
                let (finite, infinite, overflow) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!(
                    "{finite} = fcmp one double {source}, 0x7FF0000000000000"
                ));
                self.line(format!(
                    "{infinite} = fcmp oeq double {result}, 0x7FF0000000000000"
                ));
                self.line(format!("{overflow} = and i1 {finite}, {infinite}"));
                self.panic_if(&overflow, "float conversion out of range", span);
            }
            _ => unreachable!("checked numeric conversion"),
        }
        name
    }

    fn terminator(&mut self, terminator: &Terminator) {
        match terminator {
            Terminator::Goto(target) => self.line(format!("br label %bb{}", target.0)),
            Terminator::Branch {
                condition,
                then_block,
                else_block,
                ..
            } => {
                let condition = self.value(condition);
                self.line(format!(
                    "br i1 {condition}, label %bb{}, label %bb{}",
                    then_block.0, else_block.0
                ));
            }
            Terminator::Call {
                callee,
                args,
                destinations,
                target,
                unwind,
                span,
            } => {
                let result = match callee {
                    Callee::Function(id) => self.call(*id, args),
                    Callee::Println => {
                        self.println(&args[0], *span);
                        None
                    }
                    Callee::Drop => unreachable!("explicit drop is a MIR statement"),
                };
                let pending = self.fresh();
                self.line(format!("{pending} = call zeroext i1 @zore_panic_pending()"));
                let success = self.label();
                let unwind = unwind.expect("call cleanup edge");
                self.line(format!(
                    "br i1 {pending}, label %bb{}, label %{success}",
                    unwind.0
                ));
                self.out.push_str(&format!("{success}:\n"));
                if let Some((ret, value)) = result {
                    if let [destination] = &destinations[..] {
                        if let Some(place) = destination {
                            self.store(place, &value);
                        }
                    } else {
                        for (index, destination) in destinations.iter().enumerate() {
                            if let Some(place) = destination {
                                let extracted = self.fresh();
                                self.line(format!(
                                    "{extracted} = extractvalue {ret} {value}, {index}"
                                ));
                                self.store(place, &extracted);
                            }
                        }
                    }
                }
                self.line(format!("br label %bb{}", target.0));
            }
            Terminator::Assert {
                place,
                rvalue,
                target,
                unwind,
                span,
            } => {
                self.active_unwind = *unwind;
                self.assign_rvalue(place, rvalue, *span);
                self.active_unwind = None;
                self.line(format!("br label %bb{}", target.0));
            }
            Terminator::Return => {
                let package = self.module.package;
                let results = &package.function(self.body.function).results;
                match &self.body.returns[..] {
                    [] => self.line("ret void"),
                    [one] => {
                        let value = self.value(&Operand::Copy(Place::local(*one)));
                        let ty = self.ty(results[0]);
                        self.line(format!("ret {ty} {value}"));
                    }
                    many => {
                        let ty = self.module.results_ty(results);
                        let mut current = "undef".to_string();
                        for (index, &local) in many.iter().enumerate() {
                            let field_ty = self.ty(self.local_ty(local));
                            let value = self.value(&Operand::Copy(Place::local(local)));
                            let name = self.fresh();
                            self.line(format!(
                                "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                            ));
                            current = name;
                        }
                        self.line(format!("ret {ty} {current}"));
                    }
                }
            }
            Terminator::PanicReturn => {
                let results = &self.module.package.function(self.body.function).results;
                if results.is_empty() {
                    self.line("ret void");
                } else {
                    let ty = self.module.results_ty(results);
                    self.line(format!("ret {ty} undef"));
                }
            }
            Terminator::Unreachable => self.line("unreachable"),
        }
    }

    fn call(&mut self, id: hir::FunctionId, args: &[Operand]) -> Option<(String, String)> {
        let package = self.module.package;
        let callee = package.function(id);
        let mut rendered = Vec::new();
        for arg in args {
            if let Operand::Ref(place) = arg {
                let address = self.address(place);
                rendered.push(format!("ptr {address}"));
                if !package.is_copy(self.place_ty(place)) {
                    let flags = self.flag_address(place);
                    rendered.push(format!("ptr {flags}"));
                }
                continue;
            }
            let ty = self.ty(self.operand_ty(arg));
            let value = self.value(arg);
            rendered.push(format!("{ty} {value}"));
        }
        let ret = self.module.results_ty(&callee.results);
        let target = format!(
            "@\"{}.{}\"({})",
            package.name,
            callee.name,
            rendered.join(", ")
        );
        if callee.results.is_empty() {
            self.line(format!("call void {target}"));
            return None;
        }
        let result = self.fresh();
        self.line(format!("{result} = call {ret} {target}"));
        Some((ret, result))
    }

    fn println(&mut self, arg: &Operand, span: Span) {
        let arg_ty = self.operand_ty(arg);
        let kind = self.module.package.types.kind(arg_ty);
        if let TypeKind::Float(_) = kind {
            self.module.unsupported(
                "printing floating-point values is",
                span,
                "the float text format for `println` is still TBD (§37.1)",
            );
            return;
        }
        let value = self.value(arg);
        match kind {
            TypeKind::String => {
                let (ptr, len) = self.string_parts(&value);
                self.line(format!("call void @zore_println_str(ptr {ptr}, i64 {len})"));
            }
            TypeKind::Bool => {
                self.line(format!("call void @zore_println_bool(i1 zeroext {value})"))
            }
            TypeKind::Rune => self.line(format!("call void @zore_println_rune(i32 {value})")),
            TypeKind::Int(int) => {
                let wide = if int.bits == 64 {
                    value
                } else {
                    let name = self.fresh();
                    let extend = if int.signed { "sext" } else { "zext" };
                    self.line(format!("{name} = {extend} i{} {value} to i64", int.bits));
                    name
                };
                let function = if int.signed {
                    "zore_println_i64"
                } else {
                    "zore_println_u64"
                };
                self.line(format!("call void @{function}(i64 {wide})"));
            }
            TypeKind::Float(_) | TypeKind::Struct(_) => unreachable!("checked printable type"),
        }
    }
}

fn compare_predicate(op: BinaryOp, signed: bool) -> &'static str {
    match (op, signed) {
        (BinaryOp::Eq, _) => "eq",
        (BinaryOp::NotEq, _) => "ne",
        (BinaryOp::Lt, true) => "slt",
        (BinaryOp::LtEq, true) => "sle",
        (BinaryOp::Gt, true) => "sgt",
        (BinaryOp::GtEq, true) => "sge",
        (BinaryOp::Lt, false) => "ult",
        (BinaryOp::LtEq, false) => "ule",
        (BinaryOp::Gt, false) => "ugt",
        (BinaryOp::GtEq, false) => "uge",
        _ => unreachable!("not a comparison"),
    }
}
