//! Every MIR local gets a stack slot; LLVM promotes them to registers.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::fmt::Write;

use super::abi;

use crate::ast::{BinaryOp, UnaryOp};
use crate::diagnostic::{Diagnostic, Severity};
use crate::hir::{self, Const};
use crate::mir::{self, AggregateKind, Callee, Local, Operand, Place, Rvalue, Terminator};
use crate::resolve::{FieldId, FunctionId};
use crate::source::{Sources, Span};
use crate::types::{IntType, TypeId, TypeKind};

pub fn emit(
    package: &hir::Package,
    program: &mir::Program,
    sources: &dyn Sources,
) -> Result<String, Vec<Diagnostic>> {
    let owning_closures = program
        .bodies
        .iter()
        .flat_map(|body| &body.blocks)
        .flat_map(|block| &block.statements)
        .filter_map(|statement| match statement {
            mir::Statement::Assign {
                rvalue:
                    Rvalue::Closure {
                        function,
                        owning: true,
                        ..
                    },
                ..
            } => Some(*function),
            _ => None,
        })
        .collect();
    let mut module = Module {
        package,
        sources,
        strings: HashMap::new(),
        intrinsics: BTreeSet::new(),
        globals: String::new(),
        diagnostics: Vec::new(),
        owning_closures,
        task_shapes: HashMap::new(),
        task_code: String::new(),
        channel_destroyers: HashMap::new(),
    };
    let mut functions = String::new();
    for body in &program.bodies {
        functions.push_str(&module.function(body));
    }
    if !module.diagnostics.is_empty() {
        return Err(module.diagnostics);
    }
    let mut out = String::from("; Generated by the Zore bootstrap compiler.\n\n");
    out.push_str(&module.type_declarations());
    out.push('\n');
    out.push_str(&module.globals);
    out.push_str(abi::RUNTIME_DECLARATIONS);
    for intrinsic in &module.intrinsics {
        out.push_str(intrinsic);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&functions);
    out.push_str(&module.task_code);
    if let Some(entry) = program.entry {
        out.push_str(&module.entry_shim(entry));
    }
    Ok(out)
}

pub(super) struct Module<'a> {
    pub(super) package: &'a hir::Package,
    pub(super) sources: &'a dyn Sources,
    pub(super) strings: HashMap<Vec<u8>, String>,
    pub(super) intrinsics: BTreeSet<String>,
    pub(super) globals: String,
    pub(super) diagnostics: Vec<Diagnostic>,
    pub(super) owning_closures: HashSet<FunctionId>,
    /// Result lists that already have a task entry function.
    pub(super) task_shapes: HashMap<Vec<TypeId>, usize>,
    pub(super) task_code: String,
    /// Element types that already have a function destroying a queued value.
    pub(super) channel_destroyers: HashMap<TypeId, usize>,
}

/// An owning closure's heap environment: capture pointers first, then each value and its flags.
pub(super) struct Environment {
    pub(super) ty: String,
    /// Per capture: its type, its value field, and its flags field for a Move value.
    pub(super) fields: Vec<(TypeId, usize, Option<usize>)>,
}

impl Module<'_> {
    pub(super) fn environment(&self, closure: FunctionId) -> Environment {
        let function = self.package.function(closure);
        let mut parts = Vec::new();
        let mut fields = Vec::new();
        let mut pointers = 0;
        for &capture in &function.captures {
            let ty = function.locals[capture.0 as usize].ty;
            parts.push(self.ty(ty));
            let value = parts.len();
            pointers += 1;
            let flags = self.package.needs_drop(ty).then(|| {
                parts.push(self.flag_ty(ty));
                pointers += 1;
                parts.len()
            });
            fields.push((ty, value, flags));
        }
        let mut ty = format!("{{ [{pointers} x ptr]");
        for part in parts {
            write!(ty, ", {part}").unwrap();
        }
        ty.push_str(" }");
        Environment { ty, fields }
    }

    fn closure_name(&self, closure: FunctionId) -> String {
        format!(
            "@\"{}.{}\"",
            self.package.name,
            self.package.function(closure).name
        )
    }

    pub(super) fn environment_drop_name(&self, closure: FunctionId) -> String {
        format!(
            "@\"{}.{}.drop\"",
            self.package.name,
            self.package.function(closure).name
        )
    }
    pub(super) fn string_global(&mut self, bytes: &[u8]) -> String {
        if let Some(name) = self.strings.get(bytes) {
            return name.clone();
        }
        let name = format!("@str.{}", self.strings.len());
        let mut escaped = String::new();
        for &b in bytes {
            if b.is_ascii_graphic() && b != b'"' && b != b'\\' || b == b' ' {
                escaped.push(b as char);
            } else {
                write!(escaped, "\\{b:02X}").unwrap();
            }
        }
        writeln!(
            self.globals,
            "{name} = private unnamed_addr constant [{} x i8] c\"{escaped}\"",
            bytes.len()
        )
        .unwrap();
        self.strings.insert(bytes.to_vec(), name.clone());
        name
    }

    pub(super) fn location(&self, span: Span) -> String {
        match self.sources.locate(span) {
            Some((path, at)) => format!("{path}:{}:{}", at.line, at.column),
            None => "<unknown>".to_string(),
        }
    }

    pub(super) fn overflow_intrinsic(&mut self, op: &str, ty: &str) -> String {
        let name = format!("@llvm.{op}.with.overflow.{ty}");
        self.intrinsics
            .insert(format!("declare {{ {ty}, i1 }} {name}({ty}, {ty})"));
        name
    }

    pub(super) fn unsupported(&mut self, what: &str, span: Span, note: &str) {
        self.diagnostics.push(
            Diagnostic::new(
                Severity::Error,
                format!("{what} not supported by the native backend yet"),
                span,
            )
            .note(note.to_owned()),
        );
    }

    pub(super) fn types(&self) -> &crate::types::TypeStore {
        &self.package.types
    }

    pub(super) fn function(&mut self, body: &mir::Body) -> String {
        if self.package.function(body.function).native {
            return self.native_function(body);
        }
        let mut f = FunctionBuilder {
            module: self,
            body,
            out: String::new(),
            next: 0,
            active_unwind: None,
            emitting_unwind: false,
            drop_check_after_store: false,
            hoisted: String::new(),
        };
        f.emit();
        let mut out = f.out;
        if self.owning_closures.contains(&body.function) {
            out.push_str(&self.environment_drop(body));
        }
        out
    }

    /// Destroys the captured values a call has not consumed, newest first, then frees the storage.
    fn environment_drop(&mut self, body: &mir::Body) -> String {
        let closure = body.function;
        let environment = self.environment(closure);
        let name = self.environment_drop_name(closure);
        let mut f = FunctionBuilder {
            module: self,
            body,
            out: String::new(),
            next: 0,
            active_unwind: None,
            emitting_unwind: false,
            drop_check_after_store: false,
            hoisted: String::new(),
        };
        for &(ty, value, flags) in environment.fields.iter().rev() {
            let Some(flags) = flags else {
                continue;
            };
            let slot = f.fresh();
            f.line(format!(
                "{slot} = getelementptr inbounds {}, ptr %env, i32 0, i32 {value}",
                environment.ty
            ));
            let flag_slot = f.fresh();
            f.line(format!(
                "{flag_slot} = getelementptr inbounds {}, ptr %env, i32 0, i32 {flags}",
                environment.ty
            ));
            f.drop_value(&slot, ty, &flag_slot);
        }
        let size = f.byte_size(&environment.ty, "1");
        f.line(format!("call void @zore_free(ptr %env, i64 {size})"));
        f.line("ret void");
        format!(
            "define private void {name}(ptr %env) {{\nentry:\n{}{}}}\n\n",
            f.hoisted, f.out
        )
    }
}

pub(super) struct FunctionBuilder<'m, 'a> {
    pub(super) module: &'m mut Module<'a>,
    pub(super) body: &'m mir::Body,
    pub(super) out: String,
    pub(super) next: u32,
    pub(super) active_unwind: Option<mir::BlockId>,
    pub(super) emitting_unwind: bool,
    /// A replacement drop's panic check waits for the store that follows it.
    pub(super) drop_check_after_store: bool,
    /// Spliced into the entry block so loops never grow the stack.
    pub(super) hoisted: String,
}

impl FunctionBuilder<'_, '_> {
    pub(super) fn fresh(&mut self) -> String {
        self.next += 1;
        format!("%t{}", self.next)
    }

    pub(super) fn label(&mut self) -> String {
        self.next += 1;
        format!("L{}", self.next)
    }

    pub(super) fn line(&mut self, text: impl AsRef<str>) {
        self.out.push_str("  ");
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }

    pub(super) fn ty(&self, ty: TypeId) -> String {
        self.module.ty(ty)
    }

    pub(super) fn local_ty(&self, local: Local) -> TypeId {
        self.body.locals[local.0 as usize].ty
    }

    pub(super) fn slot_ty(&self, local: Local) -> String {
        if self.body.locals[local.0 as usize].by_reference {
            "ptr".into()
        } else {
            self.ty(self.local_ty(local))
        }
    }

    pub(super) fn place_ty(&self, place: &Place) -> TypeId {
        mir::place_type(self.module.package, &self.body.locals, place)
    }

    pub(super) fn operand_ty(&self, operand: &Operand) -> TypeId {
        match operand {
            Operand::Copy(place) | Operand::Move(place) | Operand::Ref(place) => {
                self.place_ty(place)
            }
            Operand::Const(_, ty) => *ty,
        }
    }

    pub(super) fn emit(&mut self) {
        let package = self.module.package;
        let function = package.function(self.body.function);
        let mut params = Vec::new();
        if function.is_closure {
            params.push("ptr %env".to_string());
        }
        for &param in &self.body.params {
            params.push(format!("{} %p{}", self.slot_ty(param), param.0));
            if self.body.locals[param.0 as usize].by_reference
                && package.needs_drop(self.local_ty(param))
            {
                params.push(format!("ptr %pf{}", param.0));
            }
        }
        let header = format!(
            "define {} @\"{}.{}\"({}) {{\nentry:\n",
            self.module.results_ty(&function.results),
            package.name,
            self.body.name,
            params.join(", ")
        );
        self.out.push_str(&header);
        for index in 0..self.body.locals.len() {
            let ty = self.slot_ty(Local(index as u32));
            self.line(format!("%l{index} = alloca {ty}"));
            let local = Local(index as u32);
            if package.needs_drop(self.local_ty(local)) {
                let flags = if self.body.locals[index].by_reference {
                    "ptr".to_string()
                } else {
                    self.module.flag_ty(self.local_ty(local))
                };
                self.line(format!("%lf{index} = alloca {flags}"));
            }
        }
        let entry_allocas_end = self.out.len();
        for index in 0..self.body.locals.len() {
            let local = Local(index as u32);
            if !self.body.locals[index].by_reference && package.needs_drop(self.local_ty(local)) {
                self.set_flags(&Place::local(local), false);
            }
        }
        for &param in &self.body.params {
            let ty = self.slot_ty(param);
            self.line(format!("store {ty} %p{}, ptr %l{}", param.0, param.0));
            if package.needs_drop(self.local_ty(param)) {
                if self.body.locals[param.0 as usize].by_reference {
                    self.line(format!("store ptr %pf{}, ptr %lf{}", param.0, param.0));
                } else {
                    self.set_flags(&Place::local(param), true);
                }
            }
        }
        self.load_captures();
        self.line("br label %bb0");
        for (index, block) in self.body.blocks.iter().enumerate() {
            self.emitting_unwind = self.body.unwind == Some(mir::BlockId(index as u32));
            self.out.push_str(&format!("bb{index}:\n"));
            for statement in &block.statements {
                self.statement(statement);
            }
            self.terminator(&block.terminator);
        }
        let hoisted = std::mem::take(&mut self.hoisted);
        self.out.insert_str(entry_allocas_end, &hoisted);
        self.out.push_str("}\n\n");
    }

    /// Per capture, the environment holds its address, then its drop flags' address for a Move value.
    fn load_captures(&mut self) {
        let mut slot = 0;
        for &capture in &self.body.captures {
            let mut targets = vec![format!("%l{}", capture.0)];
            if self.module.package.needs_drop(self.local_ty(capture)) {
                targets.push(format!("%lf{}", capture.0));
            }
            for target in targets {
                let entry = self.fresh();
                self.line(format!(
                    "{entry} = getelementptr inbounds ptr, ptr %env, i64 {slot}"
                ));
                let pointer = self.fresh();
                self.line(format!("{pointer} = load ptr, ptr {entry}"));
                self.line(format!("store ptr {pointer}, ptr {target}"));
                slot += 1;
            }
        }
    }

    fn closure_value(
        &mut self,
        function: FunctionId,
        captures: &[(Place, bool)],
        owning: bool,
    ) -> String {
        if owning {
            return self.owning_closure_value(function, captures);
        }
        let package = self.module.package;
        let mut pointers = Vec::new();
        for (place, _) in captures {
            pointers.push(self.address(place));
            if package.needs_drop(self.place_ty(place)) {
                pointers.push(self.flag_address(place));
            }
        }
        let environment = if pointers.is_empty() {
            "null".to_string()
        } else {
            // A site stores the same addresses every run, so one slot serves all its values.
            let environment = self.fresh();
            self.hoist_alloca(&environment, &format!("[{} x ptr]", pointers.len()));
            for (index, pointer) in pointers.iter().enumerate() {
                let entry = self.fresh();
                self.line(format!(
                    "{entry} = getelementptr inbounds ptr, ptr {environment}, i64 {index}"
                ));
                self.line(format!("store ptr {pointer}, ptr {entry}"));
            }
            environment
        };
        let code = self.module.closure_name(function);
        self.closure_triple(&code, &environment, "null")
    }

    fn closure_triple(&mut self, code: &str, environment: &str, drop: &str) -> String {
        let mut value = "undef".to_string();
        for (index, field) in [code, environment, drop].into_iter().enumerate() {
            let next = self.fresh();
            self.line(format!(
                "{next} = insertvalue {{ ptr, ptr, ptr }} {value}, ptr {field}, {index}"
            ));
            value = next;
        }
        value
    }

    /// Copies or moves each capture into heap storage that the closure value owns.
    fn owning_closure_value(&mut self, function: FunctionId, captures: &[(Place, bool)]) -> String {
        let environment = self.module.environment(function);
        let size = self.byte_size(&environment.ty, "1");
        let block = self.fresh();
        self.line(format!("{block} = call ptr @zore_alloc(i64 {size})"));
        let mut pointer = 0;
        for ((place, exclusive), &(ty, value, flags)) in captures.iter().zip(&environment.fields) {
            let operand =
                mir::captured_operand(self.module.package, &self.body.locals, place, *exclusive);
            let loaded = self.owned_value(&operand);
            let slot = self.environment_field(&environment, &block, value);
            self.line(format!("store {} {loaded}, ptr {slot}", self.ty(ty)));
            self.store_environment_pointer(&environment, &block, pointer, &slot);
            pointer += 1;
            if let Some(flags) = flags {
                let flag_slot = self.environment_field(&environment, &block, flags);
                self.init_flags_true(&flag_slot, ty);
                self.store_environment_pointer(&environment, &block, pointer, &flag_slot);
                pointer += 1;
            }
        }
        let code = self.module.closure_name(function);
        let drop = self.module.environment_drop_name(function);
        self.closure_triple(&code, &block, &drop)
    }

    fn environment_field(
        &mut self,
        environment: &Environment,
        block: &str,
        field: usize,
    ) -> String {
        let slot = self.fresh();
        self.line(format!(
            "{slot} = getelementptr inbounds {}, ptr {block}, i32 0, i32 {field}",
            environment.ty
        ));
        slot
    }

    fn store_environment_pointer(
        &mut self,
        environment: &Environment,
        block: &str,
        index: usize,
        pointer: &str,
    ) {
        let entry = self.fresh();
        self.line(format!(
            "{entry} = getelementptr inbounds {}, ptr {block}, i32 0, i32 0, i64 {index}",
            environment.ty
        ));
        self.line(format!("store ptr {pointer}, ptr {entry}"));
    }

    /// Indexing a slice continues from the element its data pointer designates.
    pub(super) fn address(&mut self, place: &Place) -> String {
        let mut base = format!("%l{}", place.local.0);
        if self.body.locals[place.local.0 as usize].by_reference {
            let referent = self.fresh();
            self.line(format!("{referent} = load ptr, ptr {base}"));
            base = referent;
        }
        let mut ty = self.local_ty(place.local);
        let mut gep_root = ty;
        let mut indices = String::new();
        for projection in &place.projections {
            match projection {
                mir::Projection::Field(f) => write!(indices, ", i32 {}", f.0).unwrap(),
                mir::Projection::Index(operand) => {
                    let value = self.value(operand);
                    let descriptor_element = match self.module.package.types.kind(ty) {
                        TypeKind::Slice { element, .. } | TypeKind::DynArray { element } => {
                            Some(element)
                        }
                        TypeKind::String => Some(crate::types::TypeStore::UINT8),
                        _ => None,
                    };
                    if let Some(element) = descriptor_element {
                        base = self.element_pointer(&base, gep_root, &mut indices);
                        let data = self.slice_data(&base);
                        let element_address = self.fresh();
                        self.line(format!(
                            "{element_address} = getelementptr inbounds {}, ptr {data}, i64 {value}",
                            self.ty(element)
                        ));
                        base = element_address;
                        gep_root = element;
                    } else {
                        write!(indices, ", i64 {value}").unwrap();
                    }
                }
            }
            ty = mir::projection_type(self.module.package, ty, projection);
        }
        self.element_pointer(&base, gep_root, &mut indices)
    }

    fn element_pointer(&mut self, base: &str, root: TypeId, indices: &mut String) -> String {
        if indices.is_empty() {
            return base.to_string();
        }
        let name = self.fresh();
        self.line(format!(
            "{name} = getelementptr inbounds {}, ptr {base}, i32 0{indices}",
            self.ty(root)
        ));
        indices.clear();
        name
    }

    fn slice_data(&mut self, address: &str) -> String {
        let descriptor = self.fresh();
        self.line(format!("{descriptor} = load {{ ptr, i64 }}, ptr {address}"));
        let data = self.fresh();
        self.line(format!(
            "{data} = extractvalue {{ ptr, i64 }} {descriptor}, 0"
        ));
        data
    }

    fn string_position(
        &mut self,
        string: &Operand,
        position: &Operand,
    ) -> (String, String, String) {
        let value = self.value(string);
        let (data, len) = self.string_parts(&value);
        let position = self.widen_to_i64(position);
        (data, len, position)
    }

    /// Bounds are checked first, then that both ends start characters.
    fn string_slice(
        &mut self,
        source: &Operand,
        low: Option<&Operand>,
        high: Option<&Operand>,
        span: Span,
    ) -> String {
        let value = self.value(source);
        let (data, length) = self.string_parts(&value);
        let low = low.map_or_else(|| "0".to_string(), |low| self.widen_to_i64(low));
        let high = high.map_or_else(|| length.clone(), |high| self.widen_to_i64(high));
        let high_past_end = self.fresh();
        self.line(format!("{high_past_end} = icmp ugt i64 {high}, {length}"));
        let reversed = self.fresh();
        self.line(format!("{reversed} = icmp ugt i64 {low}, {high}"));
        let invalid = self.fresh();
        self.line(format!("{invalid} = or i1 {high_past_end}, {reversed}"));
        self.panic_if(&invalid, "slice bounds out of range", span);
        let (low_start, high_start) = (self.fresh(), self.fresh());
        self.line(format!(
            "{low_start} = call zeroext i1 @zore_string_is_boundary(ptr {data}, i64 {length}, i64 {low})"
        ));
        self.line(format!(
            "{high_start} = call zeroext i1 @zore_string_is_boundary(ptr {data}, i64 {length}, i64 {high})"
        ));
        let both = self.fresh();
        self.line(format!("{both} = and i1 {low_start}, {high_start}"));
        let split = self.fresh();
        self.line(format!("{split} = xor i1 {both}, true"));
        self.panic_if(&split, "string slice not on a character boundary", span);
        let start = self.fresh();
        self.line(format!(
            "{start} = getelementptr inbounds i8, ptr {data}, i64 {low}"
        ));
        let count = self.fresh();
        self.line(format!("{count} = sub i64 {high}, {low}"));
        let with_data = self.fresh();
        self.line(format!(
            "{with_data} = insertvalue {{ ptr, i64 }} undef, ptr {start}, 0"
        ));
        let text = self.fresh();
        self.line(format!(
            "{text} = insertvalue {{ ptr, i64 }} {with_data}, i64 {count}, 1"
        ));
        self.line(format!(
            "call void @zore_string_retain(ptr {start}, i64 {count})"
        ));
        text
    }

    /// Joined text is built by the runtime and arrives with one owner.
    pub(super) fn string_concat(&mut self, left: &str, right: &str) -> String {
        let (ap, al) = self.string_parts(left);
        let (bp, bl) = self.string_parts(right);
        let out = self.fresh();
        self.hoist_alloca(&out, "{ ptr, i64 }");
        self.line(format!(
            "call void @zore_string_concat(ptr {out}, ptr {ap}, i64 {al}, ptr {bp}, i64 {bl})"
        ));
        let joined = self.fresh();
        self.line(format!("{joined} = load {{ ptr, i64 }}, ptr {out}"));
        joined
    }

    fn string_from_rune(&mut self, rune: &str) -> String {
        let out = self.fresh();
        self.hoist_alloca(&out, "{ ptr, i64 }");
        self.line(format!(
            "call void @zore_string_from_rune(ptr {out}, i32 {rune})"
        ));
        let text = self.fresh();
        self.line(format!("{text} = load {{ ptr, i64 }}, ptr {out}"));
        text
    }

    fn length(&mut self, place: &Place) -> String {
        match self.module.package.types.kind(self.place_ty(place)) {
            TypeKind::Array { size, .. } => size.to_string(),
            TypeKind::Map { .. } => {
                let address = self.address(place);
                let map = self.fresh();
                self.line(format!("{map} = load ptr, ptr {address}"));
                let length = self.fresh();
                self.line(format!("{length} = call i64 @zore_map_len(ptr {map})"));
                length
            }
            _ => self.slice_length(place),
        }
    }

    /// A by-reference local designates the referent and borrows its drop flags.
    fn bind_reference(&mut self, local: Local, rvalue: &Rvalue) {
        let (address, ty) = match rvalue {
            Rvalue::Ref(place) => (self.address(place), self.place_ty(place)),
            Rvalue::MapValueRef(map, position) => {
                let TypeKind::Map { value, .. } =
                    self.module.package.types.kind(self.place_ty(map))
                else {
                    unreachable!("a map entry reference takes a map")
                };
                let slot = self.address(map);
                let loaded = self.fresh();
                self.line(format!("{loaded} = load ptr, ptr {slot}"));
                let position = self.value(position);
                let entry = self.fresh();
                self.line(format!(
                    "{entry} = call ptr @zore_map_value_at(ptr {loaded}, i64 {position})"
                ));
                (entry, value)
            }
            _ => unreachable!("only references are bound"),
        };
        self.line(format!("store ptr {address}, ptr %l{}", local.0));
        if self.module.package.needs_drop(ty) {
            let flags = match rvalue {
                Rvalue::Ref(place)
                    if !place
                        .projections
                        .iter()
                        .any(|p| matches!(p, mir::Projection::Index(_))) =>
                {
                    self.flag_address(place)
                }
                _ => self.scratch_flags(ty),
            };
            self.line(format!("store ptr {flags}, ptr %lf{}", local.0));
        }
    }

    fn map_key_at(&mut self, map: &Place, position: &Operand) -> String {
        let TypeKind::Map { key, .. } = self.module.package.types.kind(self.place_ty(map)) else {
            unreachable!("a map key read takes a map")
        };
        let slot = self.address(map);
        let loaded = self.fresh();
        self.line(format!("{loaded} = load ptr, ptr {slot}"));
        let position = self.value(position);
        let raw = self.fresh();
        self.line(format!(
            "{raw} = call ptr @zore_map_key_at(ptr {loaded}, i64 {position})"
        ));
        let value = self.fresh();
        if key == crate::types::TypeStore::BOOL {
            let byte = self.fresh();
            self.line(format!("{byte} = load i8, ptr {raw}"));
            self.line(format!("{value} = trunc i8 {byte} to i1"));
        } else {
            let ty = self.ty(key);
            self.line(format!("{value} = load {ty}, ptr {raw}"));
        }
        if self.module.package.copies_shared(key) {
            self.retain_value(&value, key);
        }
        value
    }

    fn slice_length(&mut self, place: &Place) -> String {
        let address = self.address(place);
        let descriptor = self.fresh();
        self.line(format!("{descriptor} = load {{ ptr, i64 }}, ptr {address}"));
        let length = self.fresh();
        self.line(format!(
            "{length} = extractvalue {{ ptr, i64 }} {descriptor}, 1"
        ));
        length
    }

    /// Bounds are widened per signedness, so unsigned comparisons catch negative bounds.
    fn slice(
        &mut self,
        place: &Place,
        low: Option<&Operand>,
        high: Option<&Operand>,
        span: Span,
    ) -> String {
        let base_ty = self.place_ty(place);
        let (element, data, length) = match self.module.package.types.kind(base_ty) {
            TypeKind::Array { element, size } => {
                let array = self.address(place);
                let first = self.fresh();
                self.line(format!(
                    "{first} = getelementptr inbounds {}, ptr {array}, i64 0, i64 0",
                    self.ty(base_ty)
                ));
                (element, first, size.to_string())
            }
            TypeKind::Slice { element, .. } | TypeKind::DynArray { element } => {
                let address = self.address(place);
                let descriptor = self.fresh();
                self.line(format!("{descriptor} = load {{ ptr, i64 }}, ptr {address}"));
                let data = self.fresh();
                self.line(format!(
                    "{data} = extractvalue {{ ptr, i64 }} {descriptor}, 0"
                ));
                let length = self.fresh();
                self.line(format!(
                    "{length} = extractvalue {{ ptr, i64 }} {descriptor}, 1"
                ));
                (element, data, length)
            }
            _ => unreachable!("only arrays and slices can be sliced"),
        };
        let low = low.map_or_else(|| "0".to_string(), |low| self.widen_to_i64(low));
        let high = high.map_or_else(|| length.clone(), |high| self.widen_to_i64(high));
        let high_past_end = self.fresh();
        self.line(format!("{high_past_end} = icmp ugt i64 {high}, {length}"));
        let reversed = self.fresh();
        self.line(format!("{reversed} = icmp ugt i64 {low}, {high}"));
        let invalid = self.fresh();
        self.line(format!("{invalid} = or i1 {high_past_end}, {reversed}"));
        self.panic_if(&invalid, "slice bounds out of range", span);
        let start = self.fresh();
        self.line(format!(
            "{start} = getelementptr inbounds {}, ptr {data}, i64 {low}",
            self.ty(element)
        ));
        let count = self.fresh();
        self.line(format!("{count} = sub i64 {high}, {low}"));
        let with_data = self.fresh();
        self.line(format!(
            "{with_data} = insertvalue {{ ptr, i64 }} undef, ptr {start}, 0"
        ));
        let view = self.fresh();
        self.line(format!(
            "{view} = insertvalue {{ ptr, i64 }} {with_data}, i64 {count}, 1"
        ));
        view
    }

    pub(super) fn flag_address(&mut self, place: &Place) -> String {
        let mut current_ty = self.local_ty(place.local);
        let mut address = format!("%lf{}", place.local.0);
        if self.body.locals[place.local.0 as usize].by_reference {
            let loaded = self.fresh();
            self.line(format!("{loaded} = load ptr, ptr {address}"));
            address = loaded;
        }
        for projection in &place.projections {
            let mir::Projection::Field(field) = projection else {
                unreachable!("indexed places use scratch flags, not persistent ones")
            };
            let id = self
                .module
                .package
                .types
                .struct_id(current_ty)
                .expect("struct flag projection");
            let projected = self.fresh();
            self.line(format!(
                "{projected} = getelementptr inbounds {}, ptr {address}, i32 0, i32 {}",
                self.module.flag_ty(current_ty),
                field.0 + 1
            ));
            address = projected;
            current_ty = self.module.package.strukt(id).fields[field.0 as usize].ty;
        }
        address
    }

    pub(super) fn root_flag_address(&mut self, place: &Place) -> String {
        let address = self.flag_address(place);
        let ty = self.place_ty(place);
        self.root_flag_address_from(&address, ty)
    }

    pub(super) fn root_flag_address_from(&mut self, flags: &str, ty: TypeId) -> String {
        if matches!(self.module.package.types.kind(ty), TypeKind::Struct(_)) {
            let root = self.fresh();
            self.line(format!(
                "{root} = getelementptr inbounds {}, ptr {flags}, i32 0, i32 0",
                self.module.flag_ty(ty)
            ));
            root
        } else {
            flags.to_string()
        }
    }

    pub(super) fn set_root_flag(&mut self, place: &Place, value: bool) {
        if !self.module.package.needs_drop(self.place_ty(place)) {
            return;
        }
        let address = self.root_flag_address(place);
        self.line(format!("store i1 {value}, ptr {address}"));
    }

    pub(super) fn set_flags(&mut self, place: &Place, value: bool) {
        let ty = self.place_ty(place);
        if !self.module.package.needs_drop(ty) {
            return;
        }
        if place
            .projections
            .iter()
            .any(|p| matches!(p, mir::Projection::Index(_)))
        {
            // Array elements share the array's single flag.
            return;
        }
        self.set_root_flag(place, value);
        if let TypeKind::Struct(id) = self.module.package.types.kind(ty) {
            let count = self.module.package.strukt(id).fields.len();
            for index in 0..count {
                let mut child = place.clone();
                child
                    .projections
                    .push(mir::Projection::Field(FieldId(index as u32)));
                self.set_flags(&child, value);
            }
        }
    }

    pub(super) fn constant(&mut self, c: &Const) -> String {
        match c {
            Const::Bool(b) => b.to_string(),
            Const::Int(v) => v.to_string(),
            Const::Rune(r) => u32::from(*r).to_string(),
            Const::Float(x) => format!("0x{:016X}", x.to_bits()),
            Const::String(s) => {
                let global = self.module.string_global(s.as_bytes());
                format!("{{ ptr {global}, i64 {} }}", s.len())
            }
            Const::Nil => "{ i1 false, ptr null, i64 0 }".into(),
        }
    }

    pub(super) fn value(&mut self, operand: &Operand) -> String {
        match operand {
            Operand::Const(Const::Nil, ty)
                if self.module.package.types.task_results(*ty).is_some() =>
            {
                "null".into()
            }
            Operand::Const(c, _) => self.constant(c),
            Operand::Ref(_) => unreachable!("references are only call arguments"),
            Operand::Copy(place) | Operand::Move(place) => {
                let ty = self.ty(self.place_ty(place));
                let address = self.address(place);
                let name = self.fresh();
                self.line(format!("{name} = load {ty}, ptr {address}"));
                if matches!(operand, Operand::Move(_)) {
                    self.set_flags(place, false);
                }
                name
            }
        }
    }

    /// A value that will be kept: a Copy operand that holds text gains an owner.
    pub(super) fn owned_value(&mut self, operand: &Operand) -> String {
        let value = self.value(operand);
        if let Operand::Copy(place) = operand {
            let ty = self.place_ty(place);
            if self.module.package.copies_shared(ty) {
                self.retain_value(&value, ty);
            }
        }
        value
    }

    pub(super) fn retain_value(&mut self, value: &str, ty: TypeId) {
        if matches!(self.module.package.types.kind(ty), TypeKind::String) {
            let (data, len) = self.string_parts(value);
            self.line(format!(
                "call void @zore_string_retain(ptr {data}, i64 {len})"
            ));
            return;
        }
        let slot = self.fresh();
        let ty_text = self.ty(ty);
        self.hoist_alloca(&slot, &ty_text);
        self.line(format!("store {ty_text} {value}, ptr {slot}"));
        self.retain_at(&slot, ty);
    }

    /// Every text inside the value at `address` gains an owner.
    pub(super) fn retain_at(&mut self, address: &str, ty: TypeId) {
        if !self.module.package.holds_shared(ty) {
            return;
        }
        match self.module.package.types.kind(ty) {
            TypeKind::String => {
                let (data, len) = self.load_text(address, ty);
                self.line(format!(
                    "call void @zore_string_retain(ptr {data}, i64 {len})"
                ));
            }
            TypeKind::Error => {
                let (data, len) = self.load_text(address, ty);
                self.line(format!(
                    "call void @zore_string_retain(ptr {data}, i64 {len})"
                ));
            }
            TypeKind::Channel { .. } => self.call_on_channel("zore_channel_retain", address),
            TypeKind::Mutex { .. } => self.call_on_channel("zore_mutex_retain", address),
            TypeKind::Struct(id) => {
                let fields: Vec<TypeId> = self
                    .module
                    .package
                    .strukt(id)
                    .fields
                    .iter()
                    .map(|f| f.ty)
                    .collect();
                let struct_ty = self.ty(ty);
                for (index, field) in fields.into_iter().enumerate() {
                    if !self.module.package.holds_shared(field) {
                        continue;
                    }
                    let child = self.fresh();
                    self.line(format!(
                        "{child} = getelementptr inbounds {struct_ty}, ptr {address}, i32 0, i32 {index}"
                    ));
                    self.retain_at(&child, field);
                }
            }
            TypeKind::Array { element, size } => {
                let array_ty = self.ty(ty);
                let first = self.fresh();
                self.line(format!(
                    "{first} = getelementptr inbounds {array_ty}, ptr {address}, i64 0, i64 0"
                ));
                self.for_each_element(&first, element, &size.to_string(), |this, slot| {
                    this.retain_at(slot, element);
                });
            }
            _ => unreachable!("only Copy values hold text"),
        }
    }

    /// The bytes a string or error value reads, as a pointer and a length.
    fn load_text(&mut self, address: &str, ty: TypeId) -> (String, String) {
        let ty_text = self.ty(ty);
        let value = self.fresh();
        self.line(format!("{value} = load {ty_text}, ptr {address}"));
        if matches!(self.module.package.types.kind(ty), TypeKind::Error) {
            let (_, data, len) = self.error_parts(&value);
            (data, len)
        } else {
            self.string_parts(&value)
        }
    }

    fn call_on_channel(&mut self, function: &str, address: &str) {
        let handle = self.fresh();
        self.line(format!("{handle} = load ptr, ptr {address}"));
        self.line(format!("call void @{function}(ptr {handle})"));
    }

    pub(super) fn release_text(&mut self, address: &str, ty: TypeId) {
        let (data, len) = self.load_text(address, ty);
        self.line(format!(
            "call void @zore_string_release(ptr {data}, i64 {len})"
        ));
    }

    fn for_each_element(
        &mut self,
        data: &str,
        element: TypeId,
        count: &str,
        mut each: impl FnMut(&mut Self, &str),
    ) {
        let element_ty = self.ty(element);
        let counter = self.fresh();
        self.hoist_alloca(&counter, "i64");
        self.line(format!("store i64 0, ptr {counter}"));
        let (check, body, done) = (self.label(), self.label(), self.label());
        self.line(format!("br label %{check}"));
        self.out.push_str(&format!("{check}:\n"));
        let index = self.fresh();
        self.line(format!("{index} = load i64, ptr {counter}"));
        let more = self.fresh();
        self.line(format!("{more} = icmp ult i64 {index}, {count}"));
        self.line(format!("br i1 {more}, label %{body}, label %{done}"));
        self.out.push_str(&format!("{body}:\n"));
        let slot = self.fresh();
        self.line(format!(
            "{slot} = getelementptr inbounds {element_ty}, ptr {data}, i64 {index}"
        ));
        each(self, &slot);
        let next = self.fresh();
        self.line(format!("{next} = add i64 {index}, 1"));
        self.line(format!("store i64 {next}, ptr {counter}"));
        self.line(format!("br label %{check}"));
        self.out.push_str(&format!("{done}:\n"));
    }

    pub(super) fn store(&mut self, place: &Place, value: &str) {
        if self.module.package.copies_shared(self.place_ty(place)) {
            self.drop_place(place);
        }
        let ty = self.ty(self.place_ty(place));
        let address = self.address(place);
        self.line(format!("store {ty} {value}, ptr {address}"));
        self.set_flags(place, true);
    }

    pub(super) fn panic_if(&mut self, condition: &str, message: &str, span: Span) {
        let text = format!("{message} at {}", self.module.location(span));
        let global = self.module.string_global(text.as_bytes());
        let (fail, ok) = (self.label(), self.label());
        self.line(format!("br i1 {condition}, label %{fail}, label %{ok}"));
        self.out.push_str(&format!("{fail}:\n"));
        self.line(format!(
            "call void @zore_raise_panic(ptr {global}, i64 {})",
            text.len()
        ));
        let unwind = self
            .active_unwind
            .expect("checked operation has cleanup edge");
        self.line(format!("br label %bb{}", unwind.0));
        self.out.push_str(&format!("{ok}:\n"));
    }

    /// Negative signed values become huge unsigned ones and fail length checks.
    pub(super) fn widen_to_i64(&mut self, operand: &Operand) -> String {
        let int = self
            .module
            .package
            .types
            .int(self.operand_ty(operand))
            .expect("index operands are integers");
        let value = self.value(operand);
        if int.bits == 64 {
            return value;
        }
        let name = self.fresh();
        let extend = if int.signed { "sext" } else { "zext" };
        self.line(format!("{name} = {extend} i{} {value} to i64", int.bits));
        name
    }

    pub(super) fn bounds_check(&mut self, index: &Operand, length: &Operand, span: Span) -> String {
        let wide = self.widen_to_i64(index);
        let length = self.value(length);
        let out_of_range = self.fresh();
        self.line(format!("{out_of_range} = icmp uge i64 {wide}, {length}"));
        self.panic_if(&out_of_range, "index out of range", span);
        wide
    }

    pub(super) fn statement(&mut self, statement: &mir::Statement) {
        match statement {
            mir::Statement::Assign {
                place,
                rvalue,
                span,
            } => {
                self.assign_rvalue(place, rvalue, *span);
                if self.drop_check_after_store {
                    self.drop_check_after_store = false;
                    self.check_after_drop(false);
                }
            }
            mir::Statement::Drop {
                place,
                replacement,
                before_store,
            } => {
                self.drop_place(place);
                if self.emitting_unwind {
                    return;
                }
                let abort = *replacement && self.has_custom_ancestor(place);
                if *before_store && !abort {
                    self.drop_check_after_store = true;
                } else {
                    self.check_after_drop(abort);
                }
            }
            mir::Statement::EndScope(_) => unreachable!("drop insertion replaces scope markers"),
        }
    }

    pub(super) fn assign_rvalue(&mut self, place: &Place, rvalue: &Rvalue, span: Span) {
        if let Rvalue::Ref(_) | Rvalue::MapValueRef(..) = rvalue {
            self.bind_reference(place.local, rvalue);
            return;
        }
        let result_ty = self.place_ty(place);
        let value = match rvalue {
            Rvalue::Use(operand) => self.owned_value(operand),
            Rvalue::Zero => "zeroinitializer".into(),
            Rvalue::Binary(op, lhs, rhs) => self.binary(*op, lhs, rhs, span),
            Rvalue::Unary(op, operand) => self.unary(*op, operand, span),
            Rvalue::Convert(operand, to) => self.convert(operand, *to, span),
            Rvalue::Error(operand) => self.error_value(operand),
            Rvalue::BoundsCheck(index, length) => self.bounds_check(index, length, span),
            Rvalue::Length(place) => self.length(place),
            Rvalue::StringSlice { source, low, high } => {
                self.string_slice(source, low.as_ref(), high.as_ref(), span)
            }
            Rvalue::StringChar(string, position) => {
                let (data, len, position) = self.string_position(string, position);
                let rune = self.fresh();
                self.line(format!(
                    "{rune} = call i32 @zore_string_rune_at(ptr {data}, i64 {len}, i64 {position})"
                ));
                rune
            }
            Rvalue::StringAdvance(string, position) => {
                let (data, len, position) = self.string_position(string, position);
                let width = self.fresh();
                self.line(format!(
                    "{width} = call i64 @zore_string_char_width(ptr {data}, i64 {len}, i64 {position})"
                ));
                let next = self.fresh();
                self.line(format!("{next} = add i64 {position}, {width}"));
                next
            }
            Rvalue::MapKeyAt(map, position) => self.map_key_at(map, position),
            Rvalue::Ref(_) | Rvalue::MapValueRef(..) => unreachable!("bound above"),
            Rvalue::Slice {
                place, low, high, ..
            } => self.slice(place, low.as_ref(), high.as_ref(), span),
            Rvalue::Aggregate(AggregateKind::DynArray(element), operands) => {
                self.dyn_array_literal(*element, operands)
            }
            Rvalue::Closure {
                function,
                captures,
                owning,
            } => self.closure_value(*function, captures, *owning),
            Rvalue::Spawn(closure) => self.spawn(closure),
            Rvalue::Aggregate(_, operands) => {
                let ty = self.ty(result_ty);
                let mut current = "undef".to_string();
                for (index, operand) in operands.iter().enumerate() {
                    let field_ty = self.ty(self.operand_ty(operand));
                    let value = self.owned_value(operand);
                    let name = self.fresh();
                    self.line(format!(
                        "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                    ));
                    current = name;
                }
                current
            }
        };
        self.store(place, &value);
    }

    fn dyn_array_literal(&mut self, element: TypeId, operands: &[Operand]) -> String {
        if operands.is_empty() {
            return "{ ptr null, i64 0, i64 0 }".to_string();
        }
        let element_ty = self.ty(element);
        let bytes = self.byte_size(&element_ty, &operands.len().to_string());
        let data = self.fresh();
        self.line(format!("{data} = call ptr @zore_alloc(i64 {bytes})"));
        for (index, operand) in operands.iter().enumerate() {
            let value = self.owned_value(operand);
            let slot = self.fresh();
            self.line(format!(
                "{slot} = getelementptr inbounds {element_ty}, ptr {data}, i64 {index}"
            ));
            self.line(format!("store {element_ty} {value}, ptr {slot}"));
        }
        self.dyn_array_value(&data, &operands.len().to_string())
    }

    /// Storage holding exactly `length` elements.
    pub(super) fn dyn_array_value(&mut self, data: &str, length: &str) -> String {
        let mut array = "undef".to_string();
        for (index, field) in [
            format!("ptr {data}"),
            format!("i64 {length}"),
            format!("i64 {length}"),
        ]
        .iter()
        .enumerate()
        {
            let next = self.fresh();
            self.line(format!(
                "{next} = insertvalue {{ ptr, i64, i64 }} {array}, {field}, {index}"
            ));
            array = next;
        }
        array
    }

    pub(super) fn byte_size(&mut self, ty: &str, count: &str) -> String {
        let end = self.fresh();
        self.line(format!("{end} = getelementptr {ty}, ptr null, i64 {count}"));
        let bytes = self.fresh();
        self.line(format!("{bytes} = ptrtoint ptr {end} to i64"));
        bytes
    }

    fn drop_dyn_array(&mut self, address: &str, element: TypeId) {
        let descriptor = self.fresh();
        self.line(format!(
            "{descriptor} = load {{ ptr, i64, i64 }}, ptr {address}"
        ));
        let [data, length, capacity] = [0, 1, 2].map(|index| {
            let field = self.fresh();
            self.line(format!(
                "{field} = extractvalue {{ ptr, i64, i64 }} {descriptor}, {index}"
            ));
            field
        });
        self.drop_elements(&data, element, &length);
        let element_ty = self.ty(element);
        let bytes = self.byte_size(&element_ty, &capacity);
        self.line(format!("call void @zore_free(ptr {data}, i64 {bytes})"));
    }

    pub(super) fn drop_elements(&mut self, data: &str, element: TypeId, count: &str) {
        if !self.module.package.needs_drop(element) {
            return;
        }
        let element_ty = self.ty(element);
        let counter = self.fresh();
        self.hoist_alloca(&counter, "i64");
        self.line(format!("store i64 {count}, ptr {counter}"));
        let (check, body, done) = (self.label(), self.label(), self.label());
        self.line(format!("br label %{check}"));
        self.out.push_str(&format!("{check}:\n"));
        let remaining = self.fresh();
        self.line(format!("{remaining} = load i64, ptr {counter}"));
        let more = self.fresh();
        self.line(format!("{more} = icmp ugt i64 {remaining}, 0"));
        self.line(format!("br i1 {more}, label %{body}, label %{done}"));
        self.out.push_str(&format!("{body}:\n"));
        let index = self.fresh();
        self.line(format!("{index} = sub i64 {remaining}, 1"));
        self.line(format!("store i64 {index}, ptr {counter}"));
        let slot = self.fresh();
        self.line(format!(
            "{slot} = getelementptr inbounds {element_ty}, ptr {data}, i64 {index}"
        ));
        self.drop_unconditional(&slot, element);
        self.line(format!("br label %{check}"));
        self.out.push_str(&format!("{done}:\n"));
    }

    fn drop_map(&mut self, address: &str, value: TypeId) {
        let map = self.fresh();
        self.line(format!("{map} = load ptr, ptr {address}"));
        if self.module.package.needs_drop(value) {
            let length = self.fresh();
            self.line(format!("{length} = call i64 @zore_map_len(ptr {map})"));
            let counter = self.fresh();
            self.hoist_alloca(&counter, "i64");
            self.line(format!("store i64 0, ptr {counter}"));
            let (check, body, done) = (self.label(), self.label(), self.label());
            self.line(format!("br label %{check}"));
            self.out.push_str(&format!("{check}:\n"));
            let index = self.fresh();
            self.line(format!("{index} = load i64, ptr {counter}"));
            let more = self.fresh();
            self.line(format!("{more} = icmp ult i64 {index}, {length}"));
            self.line(format!("br i1 {more}, label %{body}, label %{done}"));
            self.out.push_str(&format!("{body}:\n"));
            let entry = self.fresh();
            self.line(format!(
                "{entry} = call ptr @zore_map_value_at(ptr {map}, i64 {index})"
            ));
            self.drop_unconditional(&entry, value);
            let next = self.fresh();
            self.line(format!("{next} = add i64 {index}, 1"));
            self.line(format!("store i64 {next}, ptr {counter}"));
            self.line(format!("br label %{check}"));
            self.out.push_str(&format!("{done}:\n"));
        }
        self.line(format!("call void @zore_map_free(ptr {map})"));
    }

    /// The caller branches to cleanup.
    pub(super) fn raise_panic(&mut self, message: &str, span: Span) {
        let text = format!("{message} at {}", self.module.location(span));
        let global = self.module.string_global(text.as_bytes());
        self.line(format!(
            "call void @zore_raise_panic(ptr {global}, i64 {})",
            text.len()
        ));
    }

    /// Array elements have no own flag, so they use transient scratch flags.
    pub(super) fn drop_place(&mut self, place: &Place) {
        let ty = self.place_ty(place);
        if !self.module.package.needs_drop(ty) {
            return;
        }
        let address = self.address(place);
        if place
            .projections
            .iter()
            .any(|p| matches!(p, mir::Projection::Index(_)))
        {
            self.drop_unconditional(&address, ty);
            return;
        }
        let flags = self.flag_address(place);
        self.drop_value(&address, ty, &flags);
    }

    /// The root flag comes first in `flags`.
    pub(super) fn drop_value(&mut self, address: &str, ty: TypeId, flags: &str) {
        if !self.module.package.needs_drop(ty) {
            return;
        }
        let root = self.root_flag_address_from(flags, ty);
        let live = self.fresh();
        self.line(format!("{live} = load i1, ptr {root}"));
        let (run, done) = (self.label(), self.label());
        self.line(format!("br i1 {live}, label %{run}, label %{done}"));
        self.out.push_str(&format!("{run}:\n"));
        self.line(format!("store i1 false, ptr {root}"));
        self.drop_contents(address, ty, flags);
        self.line(format!("br label %{done}"));
        self.out.push_str(&format!("{done}:\n"));
    }

    pub(super) fn drop_unconditional(&mut self, address: &str, ty: TypeId) {
        if !self.module.package.needs_drop(ty) {
            return;
        }
        let scratch = self.scratch_flags(ty);
        self.drop_contents(address, ty, &scratch);
    }

    /// Every flag starts true, with no persistent backing.
    pub(super) fn scratch_flags(&mut self, ty: TypeId) -> String {
        let ptr = self.fresh();
        let flag_ty = self.module.flag_ty(ty);
        self.hoist_alloca(&ptr, &flag_ty);
        self.init_flags_true(&ptr, ty);
        ptr
    }

    pub(super) fn hoist_alloca(&mut self, name: &str, ty: &str) {
        writeln!(self.hoisted, "  {name} = alloca {ty}").unwrap();
    }

    pub(super) fn init_flags_true(&mut self, address: &str, ty: TypeId) {
        if !self.module.package.needs_drop(ty) {
            return;
        }
        let root = self.root_flag_address_from(address, ty);
        self.line(format!("store i1 true, ptr {root}"));
        if let TypeKind::Struct(id) = self.module.package.types.kind(ty) {
            let strukt = self.module.package.strukt(id);
            for (index, field) in strukt.fields.iter().enumerate() {
                if !self.module.package.needs_drop(field.ty) {
                    continue;
                }
                let child = self.fresh();
                self.line(format!(
                    "{child} = getelementptr inbounds {}, ptr {address}, i32 0, i32 {}",
                    self.module.flag_ty(ty),
                    index + 1
                ));
                self.init_flags_true(&child, field.ty);
            }
        }
    }

    /// The value must be live and `flags` must point at its flag block.
    pub(super) fn drop_contents(&mut self, address: &str, ty: TypeId, flags: &str) {
        match self.module.package.types.kind(ty) {
            TypeKind::Struct(id) => {
                let strukt = self.module.package.strukt(id);
                let drop = strukt.drop;
                let fields = strukt.fields.len();
                if let Some(drop) = drop {
                    let name = self.module.package.function(drop).name.clone();
                    self.line("call void @zore_enter_drop()");
                    self.line(format!(
                        "call void @\"{}.{}\"(ptr {address}, ptr {flags})",
                        self.module.package.name, name
                    ));
                    self.line("call void @zore_leave_drop()");
                }
                let struct_ty = self.ty(ty);
                for index in (0..fields).rev() {
                    let field_ty = strukt.fields[index].ty;
                    let child = self.fresh();
                    self.line(format!(
                        "{child} = getelementptr inbounds {struct_ty}, ptr {address}, i32 0, i32 {index}"
                    ));
                    let child_flags = self.fresh();
                    self.line(format!(
                        "{child_flags} = getelementptr inbounds {}, ptr {flags}, i32 0, i32 {}",
                        self.module.flag_ty(ty),
                        index + 1
                    ));
                    self.drop_value(&child, field_ty, &child_flags);
                }
            }
            TypeKind::Array { element, size } => {
                let array_ty = self.ty(ty);
                for index in (0..size).rev() {
                    let child = self.fresh();
                    self.line(format!(
                        "{child} = getelementptr inbounds {array_ty}, ptr {address}, i64 0, i64 {index}"
                    ));
                    self.drop_unconditional(&child, element);
                }
            }
            TypeKind::String | TypeKind::Error => self.release_text(address, ty),
            TypeKind::Channel { .. } => self.call_on_channel("zore_channel_release", address),
            TypeKind::Mutex { .. } => self.call_on_channel("zore_mutex_release", address),
            TypeKind::DynArray { element } => self.drop_dyn_array(address, element),
            TypeKind::Map { value, .. } => self.drop_map(address, value),
            TypeKind::Func(_) => self.drop_closure(address),
            TypeKind::Task(_) => {
                let handle = self.fresh();
                self.line(format!("{handle} = load ptr, ptr {address}"));
                self.line(format!("call void @zore_task_detach(ptr {handle})"));
            }
            _ => {}
        }
    }

    /// Only an owning closure has a destructor.
    fn drop_closure(&mut self, address: &str) {
        let closure = self.fresh();
        self.line(format!(
            "{closure} = load {{ ptr, ptr, ptr }}, ptr {address}"
        ));
        let environment = self.fresh();
        self.line(format!(
            "{environment} = extractvalue {{ ptr, ptr, ptr }} {closure}, 1"
        ));
        let destructor = self.fresh();
        self.line(format!(
            "{destructor} = extractvalue {{ ptr, ptr, ptr }} {closure}, 2"
        ));
        let owning = self.fresh();
        self.line(format!("{owning} = icmp ne ptr {destructor}, null"));
        let (run, done) = (self.label(), self.label());
        self.line(format!("br i1 {owning}, label %{run}, label %{done}"));
        self.out.push_str(&format!("{run}:\n"));
        self.line(format!("call void {destructor}(ptr {environment})"));
        self.line(format!("br label %{done}"));
        self.out.push_str(&format!("{done}:\n"));
    }

    pub(super) fn has_custom_ancestor(&self, place: &Place) -> bool {
        let mut ty = self.local_ty(place.local);
        for projection in &place.projections {
            match projection {
                mir::Projection::Field(field) => {
                    let id = self
                        .module
                        .package
                        .types
                        .struct_id(ty)
                        .expect("field projection");
                    if self.module.package.strukt(id).drop.is_some() {
                        return true;
                    }
                    ty = self.module.package.strukt(id).fields[field.0 as usize].ty;
                }
                index @ mir::Projection::Index(_) => {
                    ty = mir::projection_type(self.module.package, ty, index);
                }
            }
        }
        false
    }

    pub(super) fn check_after_drop(&mut self, abort_on_panic: bool) {
        let pending = self.fresh();
        self.line(format!("{pending} = call zeroext i1 @zore_panic_pending()"));
        let (failed, ok) = (self.label(), self.label());
        self.line(format!("br i1 {pending}, label %{failed}, label %{ok}"));
        self.out.push_str(&format!("{failed}:\n"));
        if abort_on_panic {
            self.line("call void @zore_abort()");
            self.line("unreachable");
        } else {
            let unwind = self.body.unwind.expect("drop cleanup block");
            self.line(format!("br label %bb{}", unwind.0));
        }
        self.out.push_str(&format!("{ok}:\n"));
    }

    pub(super) fn string_parts(&mut self, value: &str) -> (String, String) {
        let (ptr, len) = (self.fresh(), self.fresh());
        self.line(format!("{ptr} = extractvalue {{ ptr, i64 }} {value}, 0"));
        self.line(format!("{len} = extractvalue {{ ptr, i64 }} {value}, 1"));
        (ptr, len)
    }

    pub(super) fn error_parts(&mut self, value: &str) -> (String, String, String) {
        let (present, ptr, len) = (self.fresh(), self.fresh(), self.fresh());
        self.line(format!(
            "{present} = extractvalue {{ i1, ptr, i64 }} {value}, 0"
        ));
        self.line(format!(
            "{ptr} = extractvalue {{ i1, ptr, i64 }} {value}, 1"
        ));
        self.line(format!(
            "{len} = extractvalue {{ i1, ptr, i64 }} {value}, 2"
        ));
        (present, ptr, len)
    }

    pub(super) fn error_value(&mut self, operand: &Operand) -> String {
        let value = self.owned_value(operand);
        let (ptr, len) = self.string_parts(&value);
        let (first, second, third) = (self.fresh(), self.fresh(), self.fresh());
        self.line(format!(
            "{first} = insertvalue {{ i1, ptr, i64 }} undef, i1 true, 0"
        ));
        self.line(format!(
            "{second} = insertvalue {{ i1, ptr, i64 }} {first}, ptr {ptr}, 1"
        ));
        self.line(format!(
            "{third} = insertvalue {{ i1, ptr, i64 }} {second}, i64 {len}, 2"
        ));
        third
    }

    pub(super) fn binary(
        &mut self,
        op: BinaryOp,
        lhs: &Operand,
        rhs: &Operand,
        span: Span,
    ) -> String {
        let operand_ty = self.operand_ty(lhs);
        let kind = self.module.package.types.kind(operand_ty);
        if matches!(op, BinaryOp::Shl | BinaryOp::Shr) {
            let TypeKind::Int(int) = kind else {
                unreachable!("checked shift")
            };
            return self.shift(op, int, lhs, rhs, span);
        }
        let (a, b) = (self.value(lhs), self.value(rhs));
        let ty = self.ty(operand_ty);
        let name = self.fresh();
        match kind {
            TypeKind::Int(int) => self.int_binary(op, int, &ty, &a, &b, span),
            TypeKind::Float(_) => {
                let instruction = match op {
                    BinaryOp::Add => "fadd",
                    BinaryOp::Sub => "fsub",
                    BinaryOp::Mul => "fmul",
                    BinaryOp::Div => "fdiv",
                    BinaryOp::Eq => "fcmp oeq",
                    BinaryOp::NotEq => "fcmp une",
                    BinaryOp::Lt => "fcmp olt",
                    BinaryOp::LtEq => "fcmp ole",
                    BinaryOp::Gt => "fcmp ogt",
                    BinaryOp::GtEq => "fcmp oge",
                    _ => unreachable!("checked float operator"),
                };
                self.line(format!("{name} = {instruction} {ty} {a}, {b}"));
                name
            }
            TypeKind::Bool | TypeKind::Rune => {
                let predicate = compare_predicate(op, false);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
                name
            }
            TypeKind::String => {
                if op == BinaryOp::Add {
                    return self.string_concat(&a, &b);
                }
                let (ap, al) = self.string_parts(&a);
                let (bp, bl) = self.string_parts(&b);
                let ordering = self.fresh();
                self.line(format!(
                    "{ordering} = call i32 @zore_string_compare(ptr {ap}, i64 {al}, ptr {bp}, i64 {bl})"
                ));
                let predicate = compare_predicate(op, true);
                self.line(format!("{name} = icmp {predicate} i32 {ordering}, 0"));
                name
            }
            TypeKind::Error => {
                let (apresent, aptr, alen) = self.error_parts(&a);
                let (bpresent, bptr, blen) = self.error_parts(&b);
                let same_presence = self.fresh();
                self.line(format!(
                    "{same_presence} = icmp eq i1 {apresent}, {bpresent}"
                ));
                let ordering = self.fresh();
                self.line(format!(
                    "{ordering} = call i32 @zore_string_compare(ptr {aptr}, i64 {alen}, ptr {bptr}, i64 {blen})"
                ));
                let same_message = self.fresh();
                self.line(format!("{same_message} = icmp eq i32 {ordering}, 0"));
                let equal = self.fresh();
                self.line(format!("{equal} = and i1 {same_presence}, {same_message}"));
                if op == BinaryOp::Eq {
                    equal
                } else {
                    self.line(format!("{name} = xor i1 {equal}, true"));
                    name
                }
            }
            TypeKind::Struct(_) => unreachable!("structs have no operators"),
            TypeKind::Array { .. } => unreachable!("arrays have no operators"),
            TypeKind::Slice { .. } => unreachable!("slices have no operators"),
            TypeKind::DynArray { .. } => unreachable!("dynamic arrays have no operators"),
            TypeKind::Map { .. } => unreachable!("maps have no operators"),
            TypeKind::Func(_) => unreachable!("function values have no operators"),
            TypeKind::Task(_) => unreachable!("tasks have no operators"),
            TypeKind::Channel { .. } => unreachable!("channels have no operators"),
            TypeKind::Mutex { .. } => unreachable!("mutexes have no operators"),
        }
    }

    pub(super) fn int_binary(
        &mut self,
        op: BinaryOp,
        int: IntType,
        ty: &str,
        a: &str,
        b: &str,
        span: Span,
    ) -> String {
        let sign = if int.signed { "s" } else { "u" };
        let name = self.fresh();
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                let base = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    _ => "mul",
                };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}{base}"), ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} {a}, {ty} {b})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.panic_if(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            BinaryOp::Div | BinaryOp::Rem => {
                let zero = self.fresh();
                self.line(format!("{zero} = icmp eq {ty} {b}, 0"));
                self.panic_if(&zero, "division by zero", span);
                if int.signed {
                    let (is_min, is_neg_one, both) = (self.fresh(), self.fresh(), self.fresh());
                    self.line(format!("{is_min} = icmp eq {ty} {a}, {}", int.min()));
                    self.line(format!("{is_neg_one} = icmp eq {ty} {b}, -1"));
                    self.line(format!("{both} = and i1 {is_min}, {is_neg_one}"));
                    self.panic_if(&both, "integer overflow", span);
                }
                let instruction = if op == BinaryOp::Div { "div" } else { "rem" };
                self.line(format!("{name} = {sign}{instruction} {ty} {a}, {b}"));
            }
            BinaryOp::BitAnd => self.line(format!("{name} = and {ty} {a}, {b}")),
            BinaryOp::BitOr => self.line(format!("{name} = or {ty} {a}, {b}")),
            BinaryOp::BitXor => self.line(format!("{name} = xor {ty} {a}, {b}")),
            _ => {
                let predicate = compare_predicate(op, int.signed);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
            }
        }
        name
    }

    pub(super) fn shift(
        &mut self,
        op: BinaryOp,
        int: IntType,
        lhs: &Operand,
        rhs: &Operand,
        span: Span,
    ) -> String {
        let ty = format!("i{}", int.bits);
        let value = self.value(lhs);
        let count_ty = self.operand_ty(rhs);
        let count_int = self
            .module
            .package
            .types
            .int(count_ty)
            .expect("integer count");
        let cty = format!("i{}", count_int.bits);
        let count = self.value(rhs);
        // An unsigned comparison also rejects a negative signed count.
        let invalid = self.fresh();
        self.line(format!("{invalid} = icmp uge {cty} {count}, {}", int.bits));
        self.panic_if(&invalid, "shift count out of range", span);
        let count = match count_int.bits.cmp(&int.bits) {
            std::cmp::Ordering::Equal => count,
            std::cmp::Ordering::Greater => {
                let name = self.fresh();
                self.line(format!("{name} = trunc {cty} {count} to {ty}"));
                name
            }
            std::cmp::Ordering::Less => {
                let name = self.fresh();
                self.line(format!("{name} = zext {cty} {count} to {ty}"));
                name
            }
        };
        let instruction = match (op, int.signed) {
            (BinaryOp::Shl, _) => "shl",
            (_, true) => "ashr",
            (_, false) => "lshr",
        };
        let name = self.fresh();
        self.line(format!("{name} = {instruction} {ty} {value}, {count}"));
        name
    }

    pub(super) fn unary(&mut self, op: UnaryOp, operand: &Operand, span: Span) -> String {
        let operand_ty = self.operand_ty(operand);
        let ty = self.ty(operand_ty);
        let value = self.value(operand);
        let name = self.fresh();
        match (op, self.module.package.types.kind(operand_ty)) {
            (UnaryOp::Plus, _) => return value,
            (UnaryOp::Not, _) => self.line(format!("{name} = xor i1 {value}, true")),
            (UnaryOp::Complement, _) => self.line(format!("{name} = xor {ty} {value}, -1")),
            (UnaryOp::Neg, TypeKind::Float(_)) => self.line(format!("{name} = fneg {ty} {value}")),
            (UnaryOp::Neg, TypeKind::Int(int)) => {
                let sign = if int.signed { "s" } else { "u" };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}sub"), &ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} 0, {ty} {value})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.panic_if(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            _ => unreachable!("checked unary operator"),
        }
        name
    }

    pub(super) fn convert(&mut self, operand: &Operand, to: TypeId, span: Span) -> String {
        let from = self.operand_ty(operand);
        if from == to {
            return self.owned_value(operand);
        }
        let value = self.value(operand);
        if from == crate::types::TypeStore::RUNE && to == crate::types::TypeStore::STRING {
            return self.string_from_rune(&value);
        }
        let types = &self.module.package.types;
        let (from_kind, to_kind) = (types.kind(from), types.kind(to));
        let (fty, tty) = (self.ty(from), self.ty(to));
        let name = self.fresh();
        match (from_kind, to_kind) {
            (TypeKind::Int(src), TypeKind::Int(dst)) => {
                let wide = self.fresh();
                let extend = if src.signed { "sext" } else { "zext" };
                self.line(format!("{wide} = {extend} {fty} {value} to i128"));
                let (low, high, outside) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{low} = icmp slt i128 {wide}, {}", dst.min()));
                self.line(format!("{high} = icmp sgt i128 {wide}, {}", dst.max()));
                self.line(format!("{outside} = or i1 {low}, {high}"));
                self.panic_if(&outside, "integer conversion out of range", span);
                match src.bits.cmp(&dst.bits) {
                    std::cmp::Ordering::Equal => return value,
                    std::cmp::Ordering::Greater => {
                        self.line(format!("{name} = trunc {fty} {value} to {tty}"))
                    }
                    std::cmp::Ordering::Less => {
                        self.line(format!("{name} = {extend} {fty} {value} to {tty}"))
                    }
                }
            }
            (TypeKind::Int(src), TypeKind::Float(_)) => {
                let instruction = if src.signed { "sitofp" } else { "uitofp" };
                self.line(format!("{name} = {instruction} {fty} {value} to {tty}"));
            }
            (TypeKind::Float(src), TypeKind::Int(dst)) => {
                let wide = if src.bits == 32 {
                    let w = self.fresh();
                    self.line(format!("{w} = fpext float {value} to double"));
                    w
                } else {
                    value
                };
                let truncated = self.fresh();
                self.line(format!(
                    "{truncated} = call double @llvm.trunc.f64(double {wide})"
                ));
                let low = format!("0x{:016X}", (dst.min() as f64).to_bits());
                let limit = format!("0x{:016X}", ((dst.max() + 1) as f64).to_bits());
                let (at_least, below, inside, outside) =
                    (self.fresh(), self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{at_least} = fcmp oge double {truncated}, {low}"));
                self.line(format!("{below} = fcmp olt double {truncated}, {limit}"));
                self.line(format!("{inside} = and i1 {at_least}, {below}"));
                self.line(format!("{outside} = xor i1 {inside}, true"));
                self.panic_if(&outside, "float to integer conversion out of range", span);
                let instruction = if dst.signed { "fptosi" } else { "fptoui" };
                self.line(format!(
                    "{name} = {instruction} double {truncated} to {tty}"
                ));
            }
            (TypeKind::Float(src), TypeKind::Float(dst)) if src.bits < dst.bits => {
                self.line(format!("{name} = fpext {fty} {value} to {tty}"));
            }
            (TypeKind::Float(_), TypeKind::Float(_)) => {
                self.line(format!("{name} = fptrunc {fty} {value} to {tty}"));
                let (source, result) = (self.fresh(), self.fresh());
                self.line(format!(
                    "{source} = call double @llvm.fabs.f64(double {value})"
                ));
                let narrowed = self.fresh();
                self.line(format!("{narrowed} = fpext {tty} {name} to double"));
                self.line(format!(
                    "{result} = call double @llvm.fabs.f64(double {narrowed})"
                ));
                let (finite, infinite, overflow) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!(
                    "{finite} = fcmp one double {source}, 0x7FF0000000000000"
                ));
                self.line(format!(
                    "{infinite} = fcmp oeq double {result}, 0x7FF0000000000000"
                ));
                self.line(format!("{overflow} = and i1 {finite}, {infinite}"));
                self.panic_if(&overflow, "float conversion out of range", span);
            }
            _ => unreachable!("checked numeric conversion"),
        }
        name
    }

    pub(super) fn terminator(&mut self, terminator: &Terminator) {
        match terminator {
            Terminator::Goto(target) => self.line(format!("br label %bb{}", target.0)),
            Terminator::Branch {
                condition,
                then_block,
                else_block,
                ..
            } => {
                let condition = self.value(condition);
                self.line(format!(
                    "br i1 {condition}, label %bb{}, label %bb{}",
                    then_block.0, else_block.0
                ));
            }
            Terminator::Call {
                callee,
                args,
                destinations,
                target,
                unwind,
                span,
            } => {
                let result = match callee {
                    Callee::Function(id) => self.call(*id, args),
                    Callee::Value(place) => self.call_value(place, args),
                    Callee::Clone(ty) => Some(self.clone_call(*ty, args)),
                    Callee::Println => {
                        self.println(&args[0], *span);
                        None
                    }
                    Callee::Drop => unreachable!("explicit drop is a MIR statement"),
                    Callee::MapInsertNew
                    | Callee::MapAssign
                    | Callee::MapLookup
                    | Callee::MapRemove => self.map_call(callee, args, *span),
                    Callee::ArrayPush | Callee::ArrayPop => self.array_call(callee, args),
                    Callee::TaskWait => self.task_wait(&args[0]),
                    Callee::ChannelMake(element) => Some(self.channel_make(*element, &args[0])),
                    Callee::ChannelSend => {
                        self.channel_send(args);
                        None
                    }
                    Callee::ChannelReceive => Some(self.channel_receive(args)),
                    Callee::ChannelClose => {
                        self.channel_close(args);
                        None
                    }
                    Callee::Select { cases, has_default } => {
                        Some(self.channel_select(cases, *has_default, args))
                    }
                    Callee::MutexNew(element) => Some(self.mutex_new(*element, &args[0])),
                    Callee::MutexWithLock => self.mutex_with_lock(args),
                    Callee::MutexIsPoisoned => Some(self.mutex_is_poisoned(&args[0])),
                };
                let pending = self.fresh();
                self.line(format!("{pending} = call zeroext i1 @zore_panic_pending()"));
                let success = self.label();
                let unwind = unwind.expect("call cleanup edge");
                self.line(format!(
                    "br i1 {pending}, label %bb{}, label %{success}",
                    unwind.0
                ));
                self.out.push_str(&format!("{success}:\n"));
                if let Some((ret, value)) = result {
                    if let [destination] = &destinations[..] {
                        if let Some(place) = destination {
                            self.store(place, &value);
                        }
                    } else {
                        for (index, destination) in destinations.iter().enumerate() {
                            if let Some(place) = destination {
                                let extracted = self.fresh();
                                self.line(format!(
                                    "{extracted} = extractvalue {ret} {value}, {index}"
                                ));
                                self.store(place, &extracted);
                            }
                        }
                    }
                }
                self.line(format!("br label %bb{}", target.0));
            }
            Terminator::Assert {
                place,
                rvalue,
                target,
                unwind,
                span,
            } => {
                self.active_unwind = *unwind;
                self.assign_rvalue(place, rvalue, *span);
                self.active_unwind = None;
                self.line(format!("br label %bb{}", target.0));
            }
            Terminator::Return => {
                let package = self.module.package;
                let results = &package.function(self.body.function).results;
                match &self.body.returns[..] {
                    [] => self.line("ret void"),
                    [one] => {
                        let value = self.value(&Operand::Copy(Place::local(*one)));
                        let ty = self.ty(results[0]);
                        self.line(format!("ret {ty} {value}"));
                    }
                    many => {
                        let ty = self.module.results_ty(results);
                        let mut current = "undef".to_string();
                        for (index, &local) in many.iter().enumerate() {
                            let field_ty = self.ty(self.local_ty(local));
                            let value = self.value(&Operand::Copy(Place::local(local)));
                            let name = self.fresh();
                            self.line(format!(
                                "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                            ));
                            current = name;
                        }
                        self.line(format!("ret {ty} {current}"));
                    }
                }
            }
            Terminator::PanicReturn => {
                let results = &self.module.package.function(self.body.function).results;
                if results.is_empty() {
                    self.line("ret void");
                } else {
                    let ty = self.module.results_ty(results);
                    self.line(format!("ret {ty} undef"));
                }
            }
            Terminator::Unreachable => self.line("unreachable"),
        }
    }
}

fn compare_predicate(op: BinaryOp, signed: bool) -> &'static str {
    match (op, signed) {
        (BinaryOp::Eq, _) => "eq",
        (BinaryOp::NotEq, _) => "ne",
        (BinaryOp::Lt, true) => "slt",
        (BinaryOp::LtEq, true) => "sle",
        (BinaryOp::Gt, true) => "sgt",
        (BinaryOp::GtEq, true) => "sge",
        (BinaryOp::Lt, false) => "ult",
        (BinaryOp::LtEq, false) => "ule",
        (BinaryOp::Gt, false) => "ugt",
        (BinaryOp::GtEq, false) => "uge",
        _ => unreachable!("not a comparison"),
    }
}
