//! MIR to textual LLVM IR (decision record 0001).
//!
//! Every MIR local gets a stack slot; LLVM's optimizer promotes them to
//! registers. Runtime checks required by §6.6 (integer overflow, division by
//! zero, shift counts, conversion ranges) branch to `zore_panic` with the
//! source location. Features the backend cannot compile yet are reported as
//! diagnostics instead of being miscompiled.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write;

use crate::ast::{BinaryOp, UnaryOp};
use crate::diagnostic::{Diagnostic, Severity};
use crate::hir::{self, Const};
use crate::mir::{self, Callee, Local, Operand, Place, Rvalue, Terminator};
use crate::source::{SourceFile, Span};
use crate::types::{IntType, TypeId, TypeKind};

/// Emit an LLVM module for a checked, lowered package.
pub fn emit(
    package: &hir::Package,
    program: &mir::Program,
    file: &SourceFile,
) -> Result<String, Vec<Diagnostic>> {
    let mut module = Module {
        package,
        file,
        strings: HashMap::new(),
        intrinsics: BTreeSet::new(),
        globals: String::new(),
        diagnostics: Vec::new(),
    };
    let mut functions = String::new();
    for body in &program.bodies {
        functions.push_str(&module.function(body));
    }
    if !module.diagnostics.is_empty() {
        return Err(module.diagnostics);
    }
    let mut out = String::from("; Generated by the Zore bootstrap compiler.\n\n");
    for strukt in &package.structs {
        let fields: Vec<String> = strukt.fields.iter().map(|f| module.ty(f.ty)).collect();
        writeln!(
            out,
            "%\"{}.{}\" = type {{ {} }}",
            package.name,
            strukt.name,
            fields.join(", ")
        )
        .unwrap();
    }
    out.push('\n');
    out.push_str(&module.globals);
    out.push_str(RUNTIME_DECLARATIONS);
    for intrinsic in &module.intrinsics {
        out.push_str(intrinsic);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&functions);
    if let Some(entry) = program.entry {
        let name = &package.function(entry).name;
        writeln!(
            out,
            "define void @zore_entry() {{\nentry:\n  call void @\"{}.{name}\"()\n  ret void\n}}",
            package.name
        )
        .unwrap();
    }
    Ok(out)
}

const RUNTIME_DECLARATIONS: &str = "\
declare void @zore_println_str(ptr, i64)
declare void @zore_println_i64(i64)
declare void @zore_println_u64(i64)
declare void @zore_println_bool(i1 zeroext)
declare void @zore_println_rune(i32)
declare i32 @zore_string_compare(ptr, i64, ptr, i64)
declare void @zore_panic(ptr, i64) noreturn
declare double @llvm.trunc.f64(double)
declare double @llvm.fabs.f64(double)
";

struct Module<'a> {
    package: &'a hir::Package,
    file: &'a SourceFile,
    /// Interned byte strings: contents to global name.
    strings: HashMap<Vec<u8>, String>,
    /// Declarations of the overflow intrinsics in use.
    intrinsics: BTreeSet<String>,
    globals: String,
    diagnostics: Vec<Diagnostic>,
}

impl Module<'_> {
    fn ty(&self, ty: TypeId) -> String {
        match self.package.types.kind(ty) {
            TypeKind::Bool => "i1".into(),
            TypeKind::Int(int) => format!("i{}", int.bits),
            TypeKind::Float(float) if float.bits == 32 => "float".into(),
            TypeKind::Float(_) => "double".into(),
            TypeKind::Rune => "i32".into(),
            TypeKind::String => "{ ptr, i64 }".into(),
            TypeKind::Struct(id) => {
                format!(
                    "%\"{}.{}\"",
                    self.package.name,
                    self.package.strukt(id).name
                )
            }
        }
    }

    fn results_ty(&self, results: &[TypeId]) -> String {
        match results {
            [] => "void".into(),
            [one] => self.ty(*one),
            many => {
                let fields: Vec<String> = many.iter().map(|&t| self.ty(t)).collect();
                format!("{{ {} }}", fields.join(", "))
            }
        }
    }

    /// A global holding `bytes`, shared between identical strings.
    fn string_global(&mut self, bytes: &[u8]) -> String {
        if let Some(name) = self.strings.get(bytes) {
            return name.clone();
        }
        let name = format!("@str.{}", self.strings.len());
        let mut escaped = String::new();
        for &b in bytes {
            if b.is_ascii_graphic() && b != b'"' && b != b'\\' || b == b' ' {
                escaped.push(b as char);
            } else {
                write!(escaped, "\\{b:02X}").unwrap();
            }
        }
        writeln!(
            self.globals,
            "{name} = private unnamed_addr constant [{} x i8] c\"{escaped}\"",
            bytes.len()
        )
        .unwrap();
        self.strings.insert(bytes.to_vec(), name.clone());
        name
    }

    fn location(&self, span: Span) -> String {
        let at = self.file.location(span.start()).expect("span in file");
        format!("{}:{}:{}", self.file.path().display(), at.line, at.column)
    }

    /// Name of `llvm.<op>.with.overflow` for `ty`, declaring it once.
    fn overflow_intrinsic(&mut self, op: &str, ty: &str) -> String {
        let name = format!("@llvm.{op}.with.overflow.{ty}");
        self.intrinsics
            .insert(format!("declare {{ {ty}, i1 }} {name}({ty}, {ty})"));
        name
    }

    fn unsupported(&mut self, what: &str, span: Span, note: &str) {
        self.diagnostics.push(
            Diagnostic::new(
                Severity::Error,
                format!("{what} not supported by the native backend yet"),
                span,
            )
            .note(note.to_owned()),
        );
    }

    fn function(&mut self, body: &mir::Body) -> String {
        let mut f = FunctionBuilder {
            module: self,
            body,
            out: String::new(),
            next: 0,
        };
        f.emit();
        f.out
    }
}

struct FunctionBuilder<'m, 'a> {
    module: &'m mut Module<'a>,
    body: &'m mir::Body,
    out: String,
    next: u32,
}

impl FunctionBuilder<'_, '_> {
    fn fresh(&mut self) -> String {
        self.next += 1;
        format!("%t{}", self.next)
    }

    fn label(&mut self) -> String {
        self.next += 1;
        format!("L{}", self.next)
    }

    fn line(&mut self, text: impl AsRef<str>) {
        self.out.push_str("  ");
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }

    fn ty(&self, ty: TypeId) -> String {
        self.module.ty(ty)
    }

    fn local_ty(&self, local: Local) -> TypeId {
        self.body.locals[local.0 as usize].ty
    }

    fn place_ty(&self, place: &Place) -> TypeId {
        let package = self.module.package;
        let mut ty = self.local_ty(place.local);
        for field in &place.fields {
            let id = package.types.struct_id(ty).expect("struct projection");
            ty = package.strukt(id).fields[field.0 as usize].ty;
        }
        ty
    }

    fn operand_ty(&self, operand: &Operand) -> TypeId {
        match operand {
            Operand::Copy(place) | Operand::Move(place) => self.place_ty(place),
            Operand::Const(_, ty) => *ty,
        }
    }

    fn emit(&mut self) {
        let package = self.module.package;
        let function = package.function(self.body.function);
        let params: Vec<String> = self
            .body
            .params
            .iter()
            .map(|&p| format!("{} %p{}", self.ty(self.local_ty(p)), p.0))
            .collect();
        let header = format!(
            "define {} @\"{}.{}\"({}) {{\nentry:\n",
            self.module.results_ty(&function.results),
            package.name,
            self.body.name,
            params.join(", ")
        );
        self.out.push_str(&header);
        for (index, local) in self.body.locals.iter().enumerate() {
            let ty = self.ty(local.ty);
            self.line(format!("%l{index} = alloca {ty}"));
        }
        for &param in &self.body.params {
            let ty = self.ty(self.local_ty(param));
            self.line(format!("store {ty} %p{}, ptr %l{}", param.0, param.0));
        }
        self.line("br label %bb0");
        for (index, block) in self.body.blocks.iter().enumerate() {
            self.out.push_str(&format!("bb{index}:\n"));
            for statement in &block.statements {
                self.statement(statement);
            }
            self.terminator(&block.terminator);
        }
        self.out.push_str("}\n\n");
    }

    /// Address of a place: the local's slot, projected through fields.
    fn address(&mut self, place: &Place) -> String {
        let base = format!("%l{}", place.local.0);
        if place.fields.is_empty() {
            return base;
        }
        let ty = self.ty(self.local_ty(place.local));
        let indices: String = place
            .fields
            .iter()
            .map(|f| format!(", i32 {}", f.0))
            .collect();
        let name = self.fresh();
        self.line(format!(
            "{name} = getelementptr inbounds {ty}, ptr {base}, i32 0{indices}"
        ));
        name
    }

    fn constant(&mut self, c: &Const) -> String {
        match c {
            Const::Bool(b) => b.to_string(),
            Const::Int(v) => v.to_string(),
            Const::Rune(r) => u32::from(*r).to_string(),
            // LLVM spells exact float constants as the bits of a double.
            Const::Float(x) => format!("0x{:016X}", x.to_bits()),
            Const::String(s) => {
                let global = self.module.string_global(s.as_bytes());
                format!("{{ ptr {global}, i64 {} }}", s.len())
            }
        }
    }

    /// The value of an operand, loading places.
    fn value(&mut self, operand: &Operand) -> String {
        match operand {
            Operand::Const(c, _) => self.constant(c),
            Operand::Copy(place) | Operand::Move(place) => {
                let ty = self.ty(self.place_ty(place));
                let address = self.address(place);
                let name = self.fresh();
                self.line(format!("{name} = load {ty}, ptr {address}"));
                name
            }
        }
    }

    fn store(&mut self, place: &Place, value: &str) {
        let ty = self.ty(self.place_ty(place));
        let address = self.address(place);
        self.line(format!("store {ty} {value}, ptr {address}"));
    }

    /// Branch to a panic with `message` when `condition` is true.
    fn check(&mut self, condition: &str, message: &str, span: Span) {
        let text = format!("{message} at {}", self.module.location(span));
        let global = self.module.string_global(text.as_bytes());
        let (fail, ok) = (self.label(), self.label());
        self.line(format!("br i1 {condition}, label %{fail}, label %{ok}"));
        self.out.push_str(&format!("{fail}:\n"));
        self.line(format!(
            "call void @zore_panic(ptr {global}, i64 {})",
            text.len()
        ));
        self.line("unreachable");
        self.out.push_str(&format!("{ok}:\n"));
    }

    fn statement(&mut self, statement: &mir::Statement) {
        let span = statement.span;
        let result_ty = self.place_ty(&statement.place);
        let value = match &statement.rvalue {
            Rvalue::Use(operand) => self.value(operand),
            Rvalue::Binary(op, lhs, rhs) => self.binary(*op, lhs, rhs, span),
            Rvalue::Unary(op, operand) => self.unary(*op, operand, span),
            Rvalue::Convert(operand, to) => self.convert(operand, *to, span),
            Rvalue::Aggregate(_, operands) => {
                let ty = self.ty(result_ty);
                let mut current = "undef".to_string();
                for (index, operand) in operands.iter().enumerate() {
                    let field_ty = self.ty(self.operand_ty(operand));
                    let value = self.value(operand);
                    let name = self.fresh();
                    self.line(format!(
                        "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                    ));
                    current = name;
                }
                current
            }
        };
        self.store(&statement.place, &value);
    }

    fn string_parts(&mut self, value: &str) -> (String, String) {
        let (ptr, len) = (self.fresh(), self.fresh());
        self.line(format!("{ptr} = extractvalue {{ ptr, i64 }} {value}, 0"));
        self.line(format!("{len} = extractvalue {{ ptr, i64 }} {value}, 1"));
        (ptr, len)
    }

    fn binary(&mut self, op: BinaryOp, lhs: &Operand, rhs: &Operand, span: Span) -> String {
        let operand_ty = self.operand_ty(lhs);
        let kind = self.module.package.types.kind(operand_ty);
        if matches!(op, BinaryOp::Shl | BinaryOp::Shr) {
            let TypeKind::Int(int) = kind else {
                unreachable!("checked shift")
            };
            return self.shift(op, int, lhs, rhs, span);
        }
        let (a, b) = (self.value(lhs), self.value(rhs));
        let ty = self.ty(operand_ty);
        let name = self.fresh();
        match kind {
            TypeKind::Int(int) => self.int_binary(op, int, &ty, &a, &b, span),
            TypeKind::Float(_) => {
                let instruction = match op {
                    BinaryOp::Add => "fadd",
                    BinaryOp::Sub => "fsub",
                    BinaryOp::Mul => "fmul",
                    BinaryOp::Div => "fdiv",
                    BinaryOp::Eq => "fcmp oeq",
                    // IEEE: NaN != NaN is true.
                    BinaryOp::NotEq => "fcmp une",
                    BinaryOp::Lt => "fcmp olt",
                    BinaryOp::LtEq => "fcmp ole",
                    BinaryOp::Gt => "fcmp ogt",
                    BinaryOp::GtEq => "fcmp oge",
                    _ => unreachable!("checked float operator"),
                };
                self.line(format!("{name} = {instruction} {ty} {a}, {b}"));
                name
            }
            TypeKind::Bool | TypeKind::Rune => {
                let predicate = compare_predicate(op, false);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
                name
            }
            TypeKind::String => {
                if op == BinaryOp::Add {
                    self.module.unsupported(
                        "runtime string concatenation is",
                        span,
                        "string buffer allocation is not designed yet (§41.5); constant concatenation works",
                    );
                    return "undef".into();
                }
                let (ap, al) = self.string_parts(&a);
                let (bp, bl) = self.string_parts(&b);
                let ordering = self.fresh();
                self.line(format!(
                    "{ordering} = call i32 @zore_string_compare(ptr {ap}, i64 {al}, ptr {bp}, i64 {bl})"
                ));
                let predicate = compare_predicate(op, true);
                self.line(format!("{name} = icmp {predicate} i32 {ordering}, 0"));
                name
            }
            TypeKind::Struct(_) => unreachable!("structs have no operators"),
        }
    }

    fn int_binary(
        &mut self,
        op: BinaryOp,
        int: IntType,
        ty: &str,
        a: &str,
        b: &str,
        span: Span,
    ) -> String {
        let sign = if int.signed { "s" } else { "u" };
        let name = self.fresh();
        match op {
            BinaryOp::Add | BinaryOp::Sub | BinaryOp::Mul => {
                let base = match op {
                    BinaryOp::Add => "add",
                    BinaryOp::Sub => "sub",
                    _ => "mul",
                };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}{base}"), ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} {a}, {ty} {b})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.check(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            BinaryOp::Div | BinaryOp::Rem => {
                let zero = self.fresh();
                self.line(format!("{zero} = icmp eq {ty} {b}, 0"));
                self.check(&zero, "division by zero", span);
                if int.signed {
                    let (is_min, is_neg_one, both) = (self.fresh(), self.fresh(), self.fresh());
                    self.line(format!("{is_min} = icmp eq {ty} {a}, {}", int.min()));
                    self.line(format!("{is_neg_one} = icmp eq {ty} {b}, -1"));
                    self.line(format!("{both} = and i1 {is_min}, {is_neg_one}"));
                    self.check(&both, "integer overflow", span);
                }
                let instruction = if op == BinaryOp::Div { "div" } else { "rem" };
                self.line(format!("{name} = {sign}{instruction} {ty} {a}, {b}"));
            }
            BinaryOp::BitAnd => self.line(format!("{name} = and {ty} {a}, {b}")),
            BinaryOp::BitOr => self.line(format!("{name} = or {ty} {a}, {b}")),
            BinaryOp::BitXor => self.line(format!("{name} = xor {ty} {a}, {b}")),
            _ => {
                let predicate = compare_predicate(op, int.signed);
                self.line(format!("{name} = icmp {predicate} {ty} {a}, {b}"));
            }
        }
        name
    }

    /// Shifts keep the low bits of the left operand's width; counts must be
    /// in range (§6.6, Q11).
    fn shift(
        &mut self,
        op: BinaryOp,
        int: IntType,
        lhs: &Operand,
        rhs: &Operand,
        span: Span,
    ) -> String {
        let ty = format!("i{}", int.bits);
        let value = self.value(lhs);
        let count_ty = self.operand_ty(rhs);
        let count_int = self
            .module
            .package
            .types
            .int(count_ty)
            .expect("integer count");
        let cty = format!("i{}", count_int.bits);
        let count = self.value(rhs);
        // Unsigned comparison also rejects negative signed counts.
        let invalid = self.fresh();
        self.line(format!("{invalid} = icmp uge {cty} {count}, {}", int.bits));
        self.check(&invalid, "shift count out of range", span);
        let count = match count_int.bits.cmp(&int.bits) {
            std::cmp::Ordering::Equal => count,
            std::cmp::Ordering::Greater => {
                let name = self.fresh();
                self.line(format!("{name} = trunc {cty} {count} to {ty}"));
                name
            }
            std::cmp::Ordering::Less => {
                let name = self.fresh();
                self.line(format!("{name} = zext {cty} {count} to {ty}"));
                name
            }
        };
        let instruction = match (op, int.signed) {
            (BinaryOp::Shl, _) => "shl",
            (_, true) => "ashr",
            (_, false) => "lshr",
        };
        let name = self.fresh();
        self.line(format!("{name} = {instruction} {ty} {value}, {count}"));
        name
    }

    fn unary(&mut self, op: UnaryOp, operand: &Operand, span: Span) -> String {
        let operand_ty = self.operand_ty(operand);
        let ty = self.ty(operand_ty);
        let value = self.value(operand);
        let name = self.fresh();
        match (op, self.module.package.types.kind(operand_ty)) {
            (UnaryOp::Plus, _) => return value,
            (UnaryOp::Not, _) => self.line(format!("{name} = xor i1 {value}, true")),
            (UnaryOp::Complement, _) => self.line(format!("{name} = xor {ty} {value}, -1")),
            (UnaryOp::Neg, TypeKind::Float(_)) => self.line(format!("{name} = fneg {ty} {value}")),
            (UnaryOp::Neg, TypeKind::Int(int)) => {
                let sign = if int.signed { "s" } else { "u" };
                let intrinsic = self.module.overflow_intrinsic(&format!("{sign}sub"), &ty);
                let pair = self.fresh();
                self.line(format!(
                    "{pair} = call {{ {ty}, i1 }} {intrinsic}({ty} 0, {ty} {value})"
                ));
                let overflow = self.fresh();
                self.line(format!(
                    "{overflow} = extractvalue {{ {ty}, i1 }} {pair}, 1"
                ));
                self.check(&overflow, "integer overflow", span);
                self.line(format!("{name} = extractvalue {{ {ty}, i1 }} {pair}, 0"));
            }
            _ => unreachable!("checked unary operator"),
        }
        name
    }

    /// Checked numeric conversion (§6.6).
    fn convert(&mut self, operand: &Operand, to: TypeId, span: Span) -> String {
        let from = self.operand_ty(operand);
        let value = self.value(operand);
        if from == to {
            return value;
        }
        let types = &self.module.package.types;
        let (from_kind, to_kind) = (types.kind(from), types.kind(to));
        let (fty, tty) = (self.ty(from), self.ty(to));
        let name = self.fresh();
        match (from_kind, to_kind) {
            (TypeKind::Int(src), TypeKind::Int(dst)) => {
                // Range-check in 128 bits, then resize.
                let wide = self.fresh();
                let extend = if src.signed { "sext" } else { "zext" };
                self.line(format!("{wide} = {extend} {fty} {value} to i128"));
                let (low, high, outside) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{low} = icmp slt i128 {wide}, {}", dst.min()));
                self.line(format!("{high} = icmp sgt i128 {wide}, {}", dst.max()));
                self.line(format!("{outside} = or i1 {low}, {high}"));
                self.check(&outside, "integer conversion out of range", span);
                match src.bits.cmp(&dst.bits) {
                    std::cmp::Ordering::Equal => return value,
                    std::cmp::Ordering::Greater => {
                        self.line(format!("{name} = trunc {fty} {value} to {tty}"))
                    }
                    std::cmp::Ordering::Less => {
                        self.line(format!("{name} = {extend} {fty} {value} to {tty}"))
                    }
                }
            }
            (TypeKind::Int(src), TypeKind::Float(_)) => {
                let instruction = if src.signed { "sitofp" } else { "uitofp" };
                self.line(format!("{name} = {instruction} {fty} {value} to {tty}"));
            }
            (TypeKind::Float(src), TypeKind::Int(dst)) => {
                // Truncate toward zero, then require the range; NaN and
                // infinities fail the ordered comparisons (§6.6).
                let wide = if src.bits == 32 {
                    let w = self.fresh();
                    self.line(format!("{w} = fpext float {value} to double"));
                    w
                } else {
                    value
                };
                let truncated = self.fresh();
                self.line(format!(
                    "{truncated} = call double @llvm.trunc.f64(double {wide})"
                ));
                let low = format!("0x{:016X}", (dst.min() as f64).to_bits());
                let limit = format!("0x{:016X}", ((dst.max() + 1) as f64).to_bits());
                let (at_least, below, inside, outside) =
                    (self.fresh(), self.fresh(), self.fresh(), self.fresh());
                self.line(format!("{at_least} = fcmp oge double {truncated}, {low}"));
                self.line(format!("{below} = fcmp olt double {truncated}, {limit}"));
                self.line(format!("{inside} = and i1 {at_least}, {below}"));
                self.line(format!("{outside} = xor i1 {inside}, true"));
                self.check(&outside, "float to integer conversion out of range", span);
                let instruction = if dst.signed { "fptosi" } else { "fptoui" };
                self.line(format!(
                    "{name} = {instruction} double {truncated} to {tty}"
                ));
            }
            (TypeKind::Float(src), TypeKind::Float(dst)) if src.bits < dst.bits => {
                self.line(format!("{name} = fpext {fty} {value} to {tty}"));
            }
            (TypeKind::Float(_), TypeKind::Float(_)) => {
                // Narrowing: a finite value that rounds to infinity panics.
                self.line(format!("{name} = fptrunc {fty} {value} to {tty}"));
                let (source, result) = (self.fresh(), self.fresh());
                self.line(format!(
                    "{source} = call double @llvm.fabs.f64(double {value})"
                ));
                let narrowed = self.fresh();
                self.line(format!("{narrowed} = fpext {tty} {name} to double"));
                self.line(format!(
                    "{result} = call double @llvm.fabs.f64(double {narrowed})"
                ));
                let (finite, infinite, overflow) = (self.fresh(), self.fresh(), self.fresh());
                self.line(format!(
                    "{finite} = fcmp one double {source}, 0x7FF0000000000000"
                ));
                self.line(format!(
                    "{infinite} = fcmp oeq double {result}, 0x7FF0000000000000"
                ));
                self.line(format!("{overflow} = and i1 {finite}, {infinite}"));
                self.check(&overflow, "float conversion out of range", span);
            }
            _ => unreachable!("checked numeric conversion"),
        }
        name
    }

    fn terminator(&mut self, terminator: &Terminator) {
        match terminator {
            Terminator::Goto(target) => self.line(format!("br label %bb{}", target.0)),
            Terminator::Branch {
                condition,
                then_block,
                else_block,
            } => {
                let condition = self.value(condition);
                self.line(format!(
                    "br i1 {condition}, label %bb{}, label %bb{}",
                    then_block.0, else_block.0
                ));
            }
            Terminator::Call {
                callee,
                args,
                destinations,
                target,
                span,
            } => {
                match callee {
                    Callee::Function(id) => self.call(*id, args, destinations),
                    Callee::Println => self.println(&args[0], *span),
                }
                self.line(format!("br label %bb{}", target.0));
            }
            Terminator::Return => {
                let package = self.module.package;
                let results = &package.function(self.body.function).results;
                match &self.body.returns[..] {
                    [] => self.line("ret void"),
                    [one] => {
                        let value = self.value(&Operand::Copy(Place::local(*one)));
                        let ty = self.ty(results[0]);
                        self.line(format!("ret {ty} {value}"));
                    }
                    many => {
                        let ty = self.module.results_ty(results);
                        let mut current = "undef".to_string();
                        for (index, &local) in many.iter().enumerate() {
                            let field_ty = self.ty(self.local_ty(local));
                            let value = self.value(&Operand::Copy(Place::local(local)));
                            let name = self.fresh();
                            self.line(format!(
                                "{name} = insertvalue {ty} {current}, {field_ty} {value}, {index}"
                            ));
                            current = name;
                        }
                        self.line(format!("ret {ty} {current}"));
                    }
                }
            }
            Terminator::Unreachable => self.line("unreachable"),
        }
    }

    fn call(&mut self, id: hir::FunctionId, args: &[Operand], destinations: &[Option<Place>]) {
        let package = self.module.package;
        let callee = package.function(id);
        let mut rendered = Vec::new();
        for arg in args {
            let ty = self.ty(self.operand_ty(arg));
            let value = self.value(arg);
            rendered.push(format!("{ty} {value}"));
        }
        let ret = self.module.results_ty(&callee.results);
        let target = format!(
            "@\"{}.{}\"({})",
            package.name,
            callee.name,
            rendered.join(", ")
        );
        if callee.results.is_empty() {
            self.line(format!("call void {target}"));
            return;
        }
        let result = self.fresh();
        self.line(format!("{result} = call {ret} {target}"));
        if let [destination] = destinations {
            if let Some(place) = destination {
                self.store(place, &result);
            }
            return;
        }
        for (index, destination) in destinations.iter().enumerate() {
            if let Some(place) = destination {
                let value = self.fresh();
                self.line(format!("{value} = extractvalue {ret} {result}, {index}"));
                self.store(place, &value);
            }
        }
    }

    fn println(&mut self, arg: &Operand, span: Span) {
        let arg_ty = self.operand_ty(arg);
        let kind = self.module.package.types.kind(arg_ty);
        if let TypeKind::Float(_) = kind {
            self.module.unsupported(
                "printing floating-point values is",
                span,
                "the float text format for `println` is still TBD (§37.1)",
            );
            return;
        }
        let value = self.value(arg);
        match kind {
            TypeKind::String => {
                let (ptr, len) = self.string_parts(&value);
                self.line(format!("call void @zore_println_str(ptr {ptr}, i64 {len})"));
            }
            TypeKind::Bool => {
                self.line(format!("call void @zore_println_bool(i1 zeroext {value})"))
            }
            TypeKind::Rune => self.line(format!("call void @zore_println_rune(i32 {value})")),
            TypeKind::Int(int) => {
                let wide = if int.bits == 64 {
                    value
                } else {
                    let name = self.fresh();
                    let extend = if int.signed { "sext" } else { "zext" };
                    self.line(format!("{name} = {extend} i{} {value} to i64", int.bits));
                    name
                };
                let function = if int.signed {
                    "zore_println_i64"
                } else {
                    "zore_println_u64"
                };
                self.line(format!("call void @{function}(i64 {wide})"));
            }
            TypeKind::Float(_) | TypeKind::Struct(_) => unreachable!("checked printable type"),
        }
    }
}

/// `icmp` predicate for a comparison; `signed` selects signed ordering.
fn compare_predicate(op: BinaryOp, signed: bool) -> &'static str {
    match (op, signed) {
        (BinaryOp::Eq, _) => "eq",
        (BinaryOp::NotEq, _) => "ne",
        (BinaryOp::Lt, true) => "slt",
        (BinaryOp::LtEq, true) => "sle",
        (BinaryOp::Gt, true) => "sgt",
        (BinaryOp::GtEq, true) => "sge",
        (BinaryOp::Lt, false) => "ult",
        (BinaryOp::LtEq, false) => "ule",
        (BinaryOp::Gt, false) => "ugt",
        (BinaryOp::GtEq, false) => "uge",
        _ => unreachable!("not a comparison"),
    }
}
